<?php
/**
 * Customer Registration template
 *
 * Description:
 * - Override rwd/enterprise
 * - Remove dob
 * - Remove newsletter subscription
 *
 * @category    design
 * @package     rwd_enterprise
 * @copyright Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license http://www.magento.com/license/enterprise-edition
 */
?>
<?php
/**
 * Create account form template
 *
 * @see app/design/frontend/base/default/template/customer/form/register.phtml
 */
/** @var $this Mage_Customer_Block_Form_Register */
?>
<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Register Now') ?></h1>
    </div>

    <div class="section">
        <?php echo $this->getChildHtml('form_fields_before')?>
        <?php echo $this->getMessagesBlock()->toHtml() ?>
        <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate" class="scaffold-form" enctype="multipart/form-data">
            <div class="col2-set">
                <div class="col-1">
                    <h2><?php echo $this->__('Account Information') ?></h2>
                    <div class="fieldset">
                        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
                        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
                        <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                        <ul class="form-list">
                            <li class="fields">
                                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                            </li>
                            <li>
                                <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                                <div class="input-box">
                                    <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->quoteEscape($this->__('Email Address')) ?>" class="input-text validate-email required-entry" />
                                    <span class="tooltip tooltip-email" title="Pastikan email yang Anda masukkan adalah email yang aktif untuk mendapatkan email balasan, diskon maupun penawan menarik dari kami"></span>
                                </div>
                            </li>
                        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                        <?php if ($_taxvat->isEnabled()): ?>
                            <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
                        <?php endif ?>
                         <!-- Commented to hide the user attributes by Sutrisno 12-4-2016 -->
                        <?php // $customerAttributes = $this->getChild('customer_form_user_attributes');?>
                        <?php // if ($customerAttributes): ?>
                            <?php // $customerAttributes->setShowContainer(false);?>
                            <?php // $this->restoreSessionData($customerAttributes->getForm());?>
                            <?php // echo $customerAttributes->toHtml()?>
                        <?php // endif;?>

                        <?php if($this->getShowAddressFields()): ?>
                            <li class="hidden">
                                <input type="hidden" name="create_address" value="1" />
                            </li>
                            <li class="fields">
                                <div class="field">
                                    <label for="company"><?php echo $this->__('Company') ?></label>
                                    <div class="input-box">
                                        <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->quoteEscape($this->__('Company')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                                    </div>
                                </div>
                            </li>
                        <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                            <li class="wide">
                                <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                                <div class="input-box">
                                    <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(0)) ?>" title="<?php echo $this->quoteEscape($this->__('Street Address')) ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                                </div>
                            </li>
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                            <li class="wide">
                                <label for="billing:street<?php echo $_i ?>"><?php echo $this->__('Street Address %s', $_i) ?></label>
                                <div class="input-box">
                                    <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i - 1)) ?>" title="<?php echo $this->quoteEscape($this->__('Street Address %s', $_i)) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                                </div>
                            </li>
                        <?php endfor; ?>
                            <li class="fields">
                                <div class="field">
                                    <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                                    <div class="input-box">
                                        <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->quoteEscape($this->__('City')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                                    </div>
                                </div>
                                <div class="field">
                                    <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                                    <div class="input-box">
                                        <select id="region_id" name="region_id" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                                            <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                        </select>
                                        <script type="text/javascript">
                                        //<![CDATA[
                                            $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                                        //]]>
                                        </script>
                                        <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                                    </div>
                                </div>
                            </li>
                            <li class="fields">
                                <div class="field">
                                    <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                                    <div class="input-box">
                                        <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->quoteEscape($this->__('Zip/Postal Code')) ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                                    </div>
                                </div>
                                <div class="field">
                                    <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                                    <div class="input-box">
                                        <?php echo $this->getCountryHtmlSelect() ?>
                                    </div>
                                </div>
                            </li>
                            <li class="hidden">
                                <input type="hidden" name="default_billing" value="1" />
                                <input type="hidden" name="default_shipping" value="1" />
                            </li>
                        <?php endif; ?>
                            <?php $addressAttributes = $this->getChild('customer_form_address_user_attributes');?>
                            <?php if ($addressAttributes): ?>
                                <?php $addressAttributes->setEntity($this->getAddress());?>
                                <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                                <?php $this->restoreSessionData($addressAttributes->getForm(), 'address');?>
                                <?php echo $addressAttributes->setShowContainer(false)->toHtml()?>
                            <?php endif;?>
                            <li class="fields">
                                <div class="field">
                                    <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                                    <div class="input-box">
                                        <input type="password" name="password" id="password" title="<?php echo $this->quoteEscape($this->__('Password')) ?>" class="input-text required-entry validate-password" />
                                    </div>
                                </div>
                                <div class="field">
                                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                                    <div class="input-box">
                                        <input type="password" name="confirmation" title="<?php echo $this->quoteEscape($this->__('Confirm Password')) ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                                    </div>
                                </div>
                            </li>
                            <li clas="field">
                                <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone Number') ?></label>
                                <div class="input-box">
                                    <input type="tel" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->quoteEscape($this->__('Telephone')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                                </div>
                            </li>
                        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                        <?php if ($_gender->isEnabled()): ?>
                            <li class="gender"><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
                        <?php endif ?>
                            <?php echo $this->getChildHtml('form.additional.info'); ?>
                            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                        </ul>
                        <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                    </div>
                </div>
                
                <div class="col-2">
                    <h2><?php echo $this->__('Member Card') ?></h2>
                    <p><strong><?php echo $this->__('DO YOU WANT TO INTEGRATE YOUR MEMBERSHIP CARD WITH RUPARUPA?') ?></strong></p>

                    <div class="fieldset">
                        <ul class="form-list">
                            <li class="field clearfix integratememberid">
                                <div class="input-box left">
                                    <input type="radio" name="integratememberid" id="integratememberid-yes" value="yes" />
                                    <label for="integratememberid-yes"><?php echo $this->__('Yes') ?></label>
                                </div>
                                <div class="input-box right">
                                    <input type="radio" name="integratememberid" id="integratememberid-no" value="no" />
                                    <label for="integratememberid-no"><?php echo $this->__('No') ?></label>
                                </div>
                            </li>
                            <li class="field memberid">
                                <img src="<?php echo $this->getSkinUrl('images/sample/general/logo-ace.png') ?>"
                                <label for="member_ace"><?php echo $this->__('ACE Member Id') ?></label>
                                <input type="text" name="member_ace" id="member_ace" class="input-text" />
                            </li>
                            <li class="field memberid">
                                <img src="<?php echo $this->getSkinUrl('images/sample/general/logo-informa.png') ?>"
                                <label for="member_informa"><?php echo $this->__('INFORMA Member Id') ?></label>
                                <input type="text" name="member_informa" id="member_informa" class="input-text" />
                            </li>
                            <li class="field memberid">
                                <img src="<?php echo $this->getSkinUrl('images/sample/general/logo-toyskingdom.png') ?>"
                                <label for="member_toyskingdom"><?php echo $this->__('TOYSKINGDOM Member Id') ?></label>
                                <input type="text" name="member_toyskingdom" id="member_toyskingdom" class="input-text" />
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <?php echo $this->getChildHtml('inchoo_socialconnect_register'); ?>
            <div class="buttons-set">
                <p><?php echo $this->__('Dengan membuat akun, saya menyetujui <a href="%s">Syarat dan Ketentuan</a>, serta <a href="%s">Kebijakan Privasi</a> Ruparupa', Mage::getBaseUrl().'terms-conditions/', Mage::getBaseUrl().'privacy-policy/') ?></p>
                <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
                <button type="submit" title="<?php echo $this->quoteEscape($this->__('Create Account')) ?>" class="button"><span><span><?php echo $this->__('Create Account') ?></span></span></button>
            </div>
            <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
                <input name="context" type="hidden" value="checkout" />
            <?php endif; ?>
        </form>
        <script type="text/javascript">
        //<![CDATA[
            var dataForm = new VarienForm('form-validate', true);
            <?php if($this->getShowAddressFields()): ?>
            new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
            <?php endif; ?>

            Form.getElements('form-validate').each(function(element) {
                element.setAttribute('autocomplete', 'off');
            });
        //]]>
        </script>
    </div>
</div>
