<?php
/**
 * Facebook Button
 *
 * Description:
 * - override RWD/default
 * - override Inchoo Social Connect ext
 * - Modify wording
 * 
* @category Inchoo
* @package SocialConnect
* @author Marko Martinović <marko.martinovic@inchoo.net>
* @copyright Copyright (c) Inchoo (http://inchoo.net/)
* @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
*/
?>
<?php
switch (strtolower($this->_getButtonText())) {
	case 'register':
		$_text = $this->__('Register with Facebook');
		break;
	
	case 'login':
		$_text = $this->__('Login with Facebook');
		break;
	
	case 'continue':
		$_text = $this->__('Login with Facebook');
		break;
	
	default:
		$_text = $this->_getButtonText();
		break;
}
?>
<div class="clearer">
    <div class="inchoo-socialconnect-facebook">
        <div class="inchoo-socialconnect-facebook-inner">
            <a href="<?php echo $this->escapeUrl($this->_getButtonUrl()); ?>"><?php echo $_text; ?></a>
        </div>
        <div class="inchoo-socialconnect-facebook-right"></div>
    </div>
</div>
