<?php  
/*
 * Set of Inspiration Template
 *
 * Description:
 * - Override beta/default
 *
 */
?>
<?php 
    $_helper = $this->helper('catalog/output');
    $_category = Mage::getModel('catalog/category')->loadByAttribute('url_key',  $this->getData('category_url'));
    if($_category != NULL && $_category->getIsActive()){
        $_products = Mage::getResourceModel('catalog/product_collection')
        ->addAttributeToSelect('*')
        ->setStoreId(Mage::app()->getStore()->getId())
        ->addCategoryFilter($_category)
        ->addAttributeToSort('position')
        ->setPageSize(4);
        Mage::getSingleton('cataloginventory/stock')->addInStockFilterToCollection($_products);
    }
?>

<h2>
    <?php echo $_category->getName(); ?>
    <?php if ($_products): ?> 
        <a href="<?php echo $_category->getUrl() ?>" class="see-more"><?php echo $this->__('View More') ?></a>
    <?php endif ?>
</h2>

<?php if ($_products && $_products->getSize() > 0): ?>        
    <ul class="products-grid">
    <?php $i=0; foreach ($_products->getItems() as $_product): ?>

        <?php
        $_product = Mage::getModel('catalog/product')->load($_product->getId());
        $attribute = $_product->getResource()->getAttribute('label');
        if(is_object($attribute)) {
            $attdefaultvalue = $attribute->getDefaultValue();
            $attributeValue = Mage::getModel('catalog/product')->load($_product->getId())->getlabel();
            $attributeValueName = Mage::getModel('catalog/product')->load($_product->getId())->getAttributeText('label');

            if(strlen($attributeValue) &&  ($attdefaultvalue !== $attributeValue)) {
                $labeltype = $attributeValueName;
            }else {
                $labeltype = "";
            }
        }
        ?>

        <li class="item">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <?php $_imgSize = 210; ?>
                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                <?php if ($labeltype): ?>
                    <div class="<?php echo $labeltype; ?>-label"></div>
                <?php endif; ?>
            </a>

            <div class="product-info">
                <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
                
                <?php  
                    // get DISC label
                    $_finalPrice=$_product->getFinalPrice(); 
                    $_price=$_product->getPrice();
                    $_savePercent = 100 - round(($_finalPrice / $_price)*100) .'%';
                ?>
                <div class="price-wrapper <?php echo ($_finalPrice < $_price)? 'has-sale':'' ?>">
                    <?php echo $this->getPriceHtml($_product, true) ?>

                    <?php if($_finalPrice < $_price): ?>
                        <!-- discount label -->
                        <span class="label sale">
                            <?php echo $this->__('%s OFF', $_savePercent) ?>
                        </span>
                    <?php endif; ?>
                </div>
                
                <div class="bottom-part">
                    <?php  
                        // Get NEW label
                        $today =  time();
                        $news_from_date_value = $_product->getData('news_from_date');
                        $news_to_date_value   = $_product->getData('news_to_date');
                        $is_new = false;
                        if($news_from_date_value != null){
                            if($today >= strtotime( $news_from_date_value) && $today <= strtotime($news_to_date_value) || $today >= strtotime( $news_from_date_value) && is_null($news_to_date_value)){
                                $is_new = true;
                            }   
                        }
                    ?>

                    <?php if($is_new): ?>
                        <!-- new label -->
                        <span class="label new">
                            <?php echo $this->__('New Product') ?>
                        </span>
                    <?php endif; ?>

                    <?php //@TODO: add IF statement here ?>
                    <!-- installment label -->
                    <span class="label installment">
                        <?php echo $this->__('Cicilan 0%') ?>
                    </span>
                </div>

            </div>
        </li>
    <?php endforeach ?>
    </ul>
<?php else: ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php endif ?>
