<p>
    <label for="is_create_gc"><?php echo Mage::helper('icube_creditmemo')->__('Create Gift Card Refund') ?></label>
    
    <input type="checkbox" name="creditmemo[is_create_gc]" value="1" id="is_create_gc" checked="checked">        
</p>

<p>
    <label for="billing_number"><?php echo Mage::helper('icube_creditmemo')->__('Billing Number') ?></label>
        
    <input type="text" name="creditmemo[billing_number]" id="billing_number" class="input-text" style="width: 60px; text-align: right;">        
</p>