<?php
/**
 * Remember me template
 *
 * Description:
 * - Override rwd/default
 * - custom tooltip
 *
 * @category    design
 * @package     rwd_default
 * @copyright Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license http://www.magento.com/license/enterprise-edition
 */
?>
<?php
/**
 * Customer "Remember Me" template
 *
 * @var $this Mage_Persistent_Block_Form_Remember
 */
?>
<li class="control remember-me-box">
    <?php $rememberMeId = 'remember_me' . Mage::helper('core')->getRandomString(10); ?>
    <div class="input-box">
        <input type="checkbox" name="persistent_remember_me" class="checkbox" id="<?php echo $rememberMeId; ?>"<?php if ($this->isRememberMeChecked()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->quoteEscape($this->__('Remember Me')) ?>" />
    </div>
    <label for="<?php echo $rememberMeId; ?>"><?php echo $this->__('Remember Me') ?></label>
    <span class="tooltip tooltip-rememberme"></span>
</li>
