
<div id="pointofsale_box">
    <div id="tools">
        <span id="searching"><?php echo Mage::helper('pointofsale')->__('Searching your location'); ?></span>
    </div>
    <div id="map_canvas_pointofsale"></div>
    <div id="pointofsale">
        <div id="title">
            <?php echo Mage::helper('pointofsale')->__('All our store locations'); ?>
            <?php $countries = $this->getCountries(); ?>

            <?php if (count($countries) > 1) : ?>
                <div id="country_selection">
                    <?php echo Mage::helper('pointofsale')->__('Select a country :'); ?>

                    <select id="country_place">
                        <option value="*">
                            <?php echo Mage::helper('pointofsale')->__('All countries'); ?>
                        </option>
                        <?php foreach ($countries as $country): ?>
                            <option value="<?php echo $country['code']; ?>">
                                <?php echo $country['name']; ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            <?php endif; ?>
        </div>
        <div id="pointofsale_scroll">

            <?php $i = 0; ?>
            <?php echo $this->renderScroller(); ?>
        </div>
    </div>
</div>
<div id="dirRendererBlock">
    <div id="direction_title">
        <h3><?php echo Mage::helper('pointofsale')->__('Your directions') ?></h3>
        <span><a class="render_tool" href="javascript:closeDirection()"><?php echo Mage::helper('pointofsale')->__('Close') ?></a></span> |
        <span><a class="render_tool" href="javascript:print()"><?php echo Mage::helper('pointofsale')->__('Print') ?></a>  </span>
    </div>
    <div id="directions"></div>

</div>


<script type="text/javascript"  src="http://maps.googleapis.com/maps/api/js?sensor=false&v=3">
</script>
<script type="text/javascript">

<?php echo $this->renderJs();?>

</script>
