<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Orderattr
 */
?>
<!-- BEGIN `Amasty: Order Attributes` -->
<?php
    $deliveryDate = array();
    if (Mage::helper('core')->isModuleEnabled('Amasty_Deliverydate')) {
        $deliveryDate = Mage::helper('amdeliverydate')->whatShow($this->_getPlace());
    }
    if (!empty($deliveryDate)):
?>
<div class="box-left">
<?php endif; ?>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-attributes"><?php echo $this->__('Custom Attributes'); ?></h4>
            <?php if ($editUrl = $this->getEditUrl()): ?>
                <div class="tools">&nbsp;&nbsp;<a href="<?php echo $editUrl; ?>">Edit</a></div>
            <?php endif; ?>
        </div>
        <fieldset><!--<div class="fieldset">-->
            <div class="hor-scroll">
                    <table cellspacing="0" class="form-list">
                        <?php if ($this->getList()): 
                              foreach ($this->getList() as $label => $value): ?>
                        <tr>
                            <td class="label"><label><?php echo $label; ?></label></td>
                            <td><!-- OR <td class="value"> -->
                                <fieldset>
                                    <strong>
                                        <?php
                                            if ($value) {
                                                echo nl2br(htmlentities(preg_replace('/\$/','\\\$', $value), ENT_COMPAT, "UTF-8"));
                                            } else {
                                                echo $this->__('--no value--');
                                            }
                                        ?>
                                    </strong>
                                </fieldset>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                        <?php else: ?>
                            <tr><td class="label"><label>&nbsp;</label></td><td class="value"><?php echo $this->__('No attributes for this order'); ?></td></tr>
                        <?php endif; ?>
                        
                        <?php
                        /* Custom ICUBE */
                        //
                        // Invoice
                        if (Mage::registry('current_invoice')) {
                            echo '<tr>';
                            echo '<td class="label"><label>SAP SO Number</label></td>';
                            echo '<td>';
                                echo '<fieldset>';
                                    echo '<strong>';
                                    echo Mage::registry('current_invoice')->getSapSoNumber();
                                    echo '</strong>';
                                echo '</fieldset>';
                            echo '</td>';
                            echo '</tr>';

                            $pickupVouchers = explode(',', Mage::registry('current_invoice')->getPickupVoucher()) ;

                            foreach ($pickupVouchers as $pickupVoucher) {
                                echo '<tr>';
                                echo '<td class="label">';
                                    echo ($pickupVoucher == reset($pickupVouchers)) ? '<label>'.$this->__('Pickup Voucher').'</label>' : '';
                                echo '</td>';
                                echo '<td>';
                                    echo '<fieldset>';
                                        echo '<strong>';
                                        echo $pickupVoucher;
                                        echo '</strong>';
                                    echo '</fieldset>';
                                echo '</td>';
                                echo '</tr>';
                            }

                            echo '<tr>';
                            echo '<td class="label"><label>Handling Voucher</label></td>';
                            echo '<td>';
                                echo '<fieldset>';
                                    echo '<strong>';
                                    echo Mage::registry('current_invoice')->getHandlingVoucher();
                                    echo '</strong>';
                                echo '</fieldset>';
                            echo '</td>';

                            echo '<tr>';
                            echo '<td class="label"><label>Shipping Status</label></td>';
                            echo '<td>';
                                echo '<fieldset>';
                                    echo '<strong>';
                                    echo Mage::registry('current_invoice')->getInvoiceStatus();
                                    echo '</strong>';
                                echo '</fieldset>';
                            echo '</td>';
                            echo '</tr>';
                        }

                        // Shipment
                        if (Mage::registry('current_shipment')) {
                            echo '<tr>';
                            echo '<td class="label"><label>SAP SO Number</label></td>';
                            echo '<td>';
                                echo '<fieldset>';
                                    echo '<strong>';
                                    echo Mage::registry('current_shipment')->getSapSoNumber();
                                    echo '</strong>';
                                echo '</fieldset>';
                            echo '</td>';
                            echo '</tr>';
                        }
                        ?>
                        
                    </table>
                
            </div>
        </fieldset><!--</div>-->
    </div>
    <div class="clear"></div>
<?php
    if (!empty($deliveryDate)):
?>
</div>
<?php endif; ?>
<!-- END `Amasty: Order Attributes` -->