<?php
/**
 * Customer Login template
 *
 * Description:
 * - Override beta/default
 * - simplify, remove register text/conatent, add register link
 * - add social buttons
 *
 * @category    design
 * @package     rwd_default
 * @copyright Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license http://www.magento.com/license/enterprise-edition
 */
?>
<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>
<div class="account-login<?php if (!$this->helper('customer')->isRegistrationAllowed()) echo ' login-only' ?>">
    <div class="page-title">
        <h1><?php echo $this->__('Login'); ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <div class="content-section">
        <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" class="scaffold-form">
            <?php echo $this->getBlockHtml('formkey'); ?>
            <div class="col2-set">
                <div class="col-1 registered-users">
                    <div class="content fieldset">
                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                        <ul class="form-list">
                            <li>
                                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                                <div class="input-box">
                                    <div class="input-box-inner email">
                                        <input type="email" placeholder="<?php echo $this->__('E-mail address') ?>" autocapitalize="off" autocorrect="off" spellcheck="false" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->quoteEscape($this->__('Email Address')) ?>" />
                                    </div>
                                </div>
                            </li>
                            <li>
                                <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                                <div class="input-box">
                                    <div class="input-box-inner password">
                                        <input type="password" placeholder="<?php echo $this->__('Password') ?>" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->quoteEscape($this->__('Password')) ?>" />
                                    </div>
                                </div>
                            </li>
                            <?php echo $this->getChildHtml('form.additional.info'); ?>
                            <li>
                                <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                            </li>
                            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                        </ul>
                        <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                    </div>
                    <div class="buttons-set">
                        <button type="submit" class="button" title="<?php echo $this->quoteEscape($this->__('Login')) ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>

                        <?php if (Mage::helper('core')->isModuleEnabled('Inchoo_SocialConnect')): ?>
                            <div class="a-center or"><?php echo $this->__('Or') ?></div>
                            <div class="social-connect-btn">
                            <?php
                                echo $this->getLayout()->createBlock('inchoo_socialconnect/facebook_button')->setTemplate("inchoo/socialconnect/facebook/button.phtml")->toHtml();
                            ?>
                            </div>
                            <div class="social-connect-btn">
                            <?php
                                echo $this->getLayout()->createBlock('inchoo_socialconnect/google_button')->setTemplate("inchoo/socialconnect/google/button.phtml")->toHtml();
                            ?>
                            </div>
                        <?php endif ?>
                    </div>
                    <?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
                        <div class="register-link-wrapper"><?php echo $this->__('Belum Terdaftar?') ?> <a title="<?php echo $this->quoteEscape($this->__('Create an Account')) ?>"  href="<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>"><?php echo $this->__('Klik Disini') ?></a></div>
                    <?php endif; ?>
                </div>
            </div>
            <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
                <input name="context" type="hidden" value="checkout" />
            <?php endif; ?>
        </form>
        <script type="text/javascript">
        //<![CDATA[
            var dataForm = new VarienForm('login-form', true);
        //]]>
        </script>
    </div>
</div>
