<?php
/**
 * Order History Template
 *
 * Description:
 * - override rwd/default
 * - Change header wording
 * - Remove reorder link
 * - Add table wrapper
 *
 * @category    design
 * @package     rwd_default
 * @copyright Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license http://www.magento.com/license/enterprise-edition
 */
?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<div class="section">
    <div class="page-title">
        <h1><?php echo $this->__('Your Orders') ?></h1>
    </div>
    <?php echo $this->getChildHtml('info');?>
    <?php echo $this->getPagerHtml(); ?>
    <?php if($_orders->getSize()): ?>
    <div class="data-table-wrapper">
        <table class="data-table orders" id="my-orders-table">
            <col width="1" />
            <col width="1" />
            <col />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <thead>
                <tr>
                    <th class="number"><?php echo $this->__('Order Number') ?></th>
                    <th class="date"><?php echo $this->__('Date') ?></th>
                    <th class="ship"><?php echo $this->__('Ship To') ?></th>
                    <th class="total"><span class="nobr"><?php echo $this->__('Amount') ?></span></th>
                    <th class="status"><?php echo $this->__('Status') ?></th>
                    <th class="view">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php $_odd = ''; ?>
                <?php foreach ($_orders as $_order): ?>
                <tr>
                    <td class="number" data-rwd="<?php echo $this->__('Order Number') ?>"><?php echo $_order->getRealOrderId() ?></td>
                    <td class="date" data-rwd="<?php echo $this->__('Date') ?>"><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                    <td class="ship" data-rwd="<?php echo $this->__('Ship To') ?>"><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                    <td class="total" data-rwd="<?php echo $this->__('Amount') ?>"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td class="status" data-rwd="<?php echo $this->__('Status') ?>"><?php echo $_order->getStatusLabel() ?></td>
                    <td class="a-center view">
                        <?php if(Mage::helper('core')->isModuleEnabled('Icube_TrackOrder')): ?>
                            <span class="nobr"><a href="<?php echo Mage::getBaseUrl().'trackorder/tracking/result/?orderid='.$_order->getRealOrderId().'&email='.Mage::getSingleton('customer/session')->getCustomer()->getEmail() ?>"><?php echo $this->__('Detail') ?></a>
                                <?php /*<span class="separator">|</span><a href="<?php echo $this->getTrackUrl($_order) ?>"><?php echo $this->__('Track Order') ?></a>&nbsp;*/ ?>
                            </span>
                        <?php else: ?>
                            <span class="nobr"><a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('Detail') ?></a>
                                <?php /*<span class="separator">|</span><a href="<?php echo $this->getTrackUrl($_order) ?>"><?php echo $this->__('Track Order') ?></a>&nbsp;*/ ?>
                            </span>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php else: ?>
        <p><?php echo $this->__('You have placed no orders.'); ?></p>
    <?php endif ?>
</div>
<script type="text/javascript">decorateTable('my-orders-table');</script>
