
<?php if (!Mage::getSingleton('core/session')->getPickupatstore()): ?>
    <?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>
        <?php $completeClass = $this->getCheckout()->getStepData('shipping', 'complete') ? 'complete' : ''; ?>
        <dt class="<?php echo $completeClass ?>">
        <?php echo $this->__('Shipping Address') ?> <span class="changelink"><span class="separator">|</span> <a
                href="#payment"
                onclick="checkout.changeSection('opc-shipping');
                            return false;"><?php echo $this->__('Change') ?></a></span>
        </dt>
        <dd class="<?php echo $completeClass ?>">
            <?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>
                <address><?php echo $this->getShipping()->format('html') ?></address>
            <?php endif; ?>
        </dd>
    <?php else: ?>
        <dt>
        <?php echo $this->__('Shipping Address') ?>
        </dt>
    <?php endif; ?>
<?php endif; ?>
