<?php  
/*
 * Set of Inspiration Template
 *
 * Description:
 * - Created from scratch
 *
 */
?>
<?php 
    $_helper = $this->helper('catalog/output');
    $_category = Mage::getModel('catalog/category')->loadByAttribute('url_key',  $this->getData('category_url'));
    if($_category != NULL && $_category->getIsActive()){
        $_products = Mage::getResourceModel('catalog/product_collection')
        ->addAttributeToSelect('*')
        ->setStoreId(Mage::app()->getStore()->getId())
        ->addCategoryFilter($_category)
        ->addAttributeToSort('position')
        ->setPageSize(4);
        Mage::getSingleton('cataloginventory/stock')->addInStockFilterToCollection($_products);
    }
?>

<div class="products">
<?php if ($_products && $_products->getSize() > 0): ?>        
    <ul>
    <?php $i=0; foreach ($_products->getItems() as $_product): ?>

        <?php
        $_product = Mage::getModel('catalog/product')->load($_product->getId());
        $attribute = $_product->getResource()->getAttribute('label');
        if(is_object($attribute)) {
            $attdefaultvalue = $attribute->getDefaultValue();
            $attributeValue = Mage::getModel('catalog/product')->load($_product->getId())->getlabel();
            $attributeValueName = Mage::getModel('catalog/product')->load($_product->getId())->getAttributeText('label');
            if(strlen($attributeValue) &&  ($attdefaultvalue !== $attributeValue)) {
                $labeltype = $attributeValueName;
            }else {
                $labeltype = "";
            }
        }
        ?>

        <li>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <?php $_imgSize = 210; ?>
                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                <?php if ($labeltype): ?>
                    <div class="<?php echo $labeltype; ?>-label"></div>
                <?php endif; ?>
            </a>

            <div class="product-info">
                <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
                <?php echo $this->getPriceHtml($_product, true) ?>
            </div>
        </li>
    <?php endforeach ?>
    </ul>
<?php else: ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php endif ?>
</div>
<?php if ($_products): ?>        
    <!-- <a href="<?php echo $_category->getUrl() ?>" class="button btn-line-blue see-more">View More</a> -->
<?php endif ?>