<?php
/**
 * Cart Template
 *
 * Description:
 * - Override rwd/default
 * - Remove button within page-title
 * - Disable cart forms
 * - Remove tfoot
 * - Add Shpping Column
 *
 * @category    design
 * @package     rwd_default
 * @copyright Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license http://www.magento.com/license/enterprise-edition
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @var $this Mage_Checkout_Block_Cart
 */
?>
<?php $_priceDisplay = ($this->helper('tax')->displayCartBothPrices()) ? 'display-both-prices' : 'display-single-price'; ?>
<div class="cart <?php echo $_priceDisplay; ?> cart-wrapper">
    <div class="page-title">
        <h1><?php echo $this->__('Shopping Cart') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <table id="shopping-cart-table" class="cart-table data-table">
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <col width="1" />
            <?php endif; ?>
            <col width="1" />

        <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
            <thead>
                <tr>
                    <th class="a-center" rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
                    <th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Product') ?></span></th>

                    <th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>

                    <th rowspan="<?php echo $mergedCells; ?>" class="a-center">
                        <?php echo $this->__('Quantity') ?>

                        <?php /*if ($this->helper('wishlist')->isAllowInCart()) : ?>
                            <span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span>
                        <?php endif*/ ?>

                    </th>

                    <th class="a-center cart-price-head" colspan="<?php echo $mergedCells; ?>">
<!--                            <div class="cart-price-placeholder">-->
                            <span class="nobr"><?php echo $this->__('Unit Price') ?></span>
<!--                            </div>-->
                    </th>

                    <th class="a-left shipping" colspan="<?php echo $mergedCells; ?>">
<!--                            <div class="cart-total-placeholder">-->
                            <?php echo $this->__('Shipping') ?>
<!--                            </div>-->
                    </th>

                    <th class="a-right cart-total-head" colspan="<?php echo $mergedCells; ?>">
<!--                            <div class="cart-total-placeholder">-->
                            <?php echo $this->__('Total') ?>
<!--                            </div>-->
                    </th>
                </tr>
                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <tr>
                    <th class="a-center cart-price-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th class="a-center cart-price-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    <th class="a-center cart-total-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th class="a-center cart-total-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                </tr>
                <?php endif; ?>
            </thead>
            <tbody>
            <?php foreach($this->getItems() as $_item): ?>
                <?php echo $this->getItemHtml($_item) ?>
            <?php endforeach ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('shopping-cart-table')</script>
    </form>

    <!-- <div class="cart-forms"> -->
        <?php /* Extensions placeholder */ ?>
        <?php //echo $this->getChildHtml('checkout_cart_widget') ?>
        <?php //echo $this->getChildHtml('coupon') ?>
        <?php //echo $this->getChildHtml('checkout.cart.extra') ?>
        <?php //if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
    <!-- </div> -->
    <div class="cart-totals-wrapper">
        <div class="cart-totals">
            <?php echo $this->getChildHtml('totals'); ?>
            <p class="exclude-shipping"><sup>*</sup><?php echo $this->__('exclude delivery') ?></p>
        </div>
    </div>
    <?php echo $this->getChildHtml('shopping.cart.table.after'); ?>
    <?php echo $this->getChildHtml('crosssell') ?>
</div>

<div class="page-actions">
    <div class="left">
        <?php if($this->getContinueShoppingUrl()): ?>
            <button type="button" title="<?php echo $this->quoteEscape($this->__('Continue Shopping')) ?>" class="button2 btn-continue" onclick="setLocation('<?php echo Mage::helper('core')->quoteEscape($this->getContinueShoppingUrl()) ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
        <?php endif; ?>
    </div>
    <div class="right">
        <?php if(!$this->hasError()): ?>
        <ul class="checkout-types bottom">
        <?php foreach ($this->getMethods('methods') as $method): ?>
            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
            <li class="method-<?php echo preg_replace("/[^_a-zA-Z0-9-]/", '-', $method); ?>"><?php echo $methodHtml; ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
        <?php endif; ?>
    </div>
</div>
