<?php
/**
 * shipping method Template
 *
 * Description:
 * - Override base/default
 *
 * @category    design
 * @package     base_default
 * @copyright Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license http://www.magento.com/license/enterprise-edition
 */
?>
<form id="co-shipping-method-form" action="">
    <div class="opc-content-wrapper">
        <h3><?php echo $this->__('Shipping Method') ?></h3>
        <div id="checkout-shipping-method-load">
           <!-- Content loaded dynamically -->
        </div>
        <script type="text/javascript">
        //<![CDATA[
            var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>");
        //]]>
        </script>
        <div id="onepage-checkout-shipping-method-additional-load">
            <?php echo $this->getChildHtml('additional') ?>
        </div>
    </div>
</form>

<div class="buttons-set" id="shipping-method-buttons-container">
    <a href="#" onclick="checkout.back(); return false;" class="back-link"><?php echo $this->__('Back') ?></a>
    <button type="button" class="button" onclick="shippingMethod.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
    <span id="shipping-method-please-wait" class="please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
    </span>
</div>
