<?php
/**
 * Invoice Items Template
 *
 * Description:
 * - override rwd/default
 * - wrap table with data-table-wrapper
 * - move totals to separated table
 *
 * @category    design
 * @package     rwd_default
 * @copyright Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license http://www.magento.com/license/enterprise-edition
 */
?>
<?php  $_order = $this->getOrder() ?>
<p class="order-links"><a href="<?php echo $this->getPrintAllInvoicesUrl($_order) ?>" onclick="this.target='_blank'" class="link-print"><?php echo $this->__('Print All Invoices') ?></a></p>
<?php foreach ($_order->getInvoiceCollection() as $_invoice): ?>
    <h2 class="sub-title"><?php echo $this->__('Invoice #') ?><?php echo $_invoice->getIncrementId(); ?> <span class="separator">|</span> <a href="<?php echo $this->getPrintInvoiceUrl($_invoice) ?>" onclick="this.target='_blank'" class="link-print"><?php echo $this->__('Print Invoice') ?></a></h2>
    <h3 class="table-caption"><?php echo $this->__('Items Invoiced') ?></h3>
    <div class="data-table-wrapper">
        <table class="data-table linearize-table" id="my-invoice-table-<?php echo $_invoice->getId(); ?>">
            <col />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <thead>
            <tr>
                <th><?php echo $this->__('Product Name') ?></th>
                <th class="sku"><?php echo $this->__('SKU') ?></th>
                <th class="a-right" data-rwd-label="<?php echo $this->__('Price') ?>"><?php echo $this->__('Price') ?></th>
                <th class="a-center" data-rwd-label="<?php echo $this->__('Qty Invoiced') ?>"><span class="nobr"><?php echo $this->__('Qty Invoiced') ?></span></th>
                <th class="a-right" data-rwd-label="<?php echo $this->__('Subtotal') ?>"><?php echo $this->__('Subtotal') ?></th>
            </tr>
            </thead>
            <tfoot>
            </tfoot>
            <?php $_items = $_invoice->getAllItems(); ?>
            <?php $_count = count($_items) ?>
            <?php foreach ($_items as $_item): ?>
                <?php if ($_item->getOrderItem()->getParentItem()) continue; ?>
                <tbody>
                <?php echo $this->getItemHtml($_item) ?>
                </tbody>
            <?php endforeach; ?>
        </table>
    </div>

    <table class="total"><col />
        <col />
        <col width="1" />
        <tfoot>
            <?php echo $this->getInvoiceTotalsHtml($_invoice)?>
        </tfoot>
    </table>
    <script type="text/javascript">decorateTable('my-invoice-table-<?php echo $_invoice->getId(); ?>', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
    <?php echo $this->getInvoiceCommentsHtml($_invoice)?>
<?php endforeach; ?>
