<?php
/**
 * Toolbar Template
 *
 * Description:
 * - Override default/default
 * - Rearange html structure
 * - Remove view-mode
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar">
    <div class="top">
        <div class="left">
            <!-- items counter -->
            <div class="count-container">
            <?php if ($this->getTotalNum() > 1): ?>
                <?php echo $this->__('%s Products', $this->getTotalNum()) ?>
            <?php else: ?>
                <?php echo $this->__('%s Product', $this->getTotalNum()) ?>
            <?php endif ?>
            </div>
        </div>
        <div class="right">
            <!-- Sort By -->
            <?php if( $this->isExpanded() ): ?>
                <div class="sorter">
                    <div class="sort-by">
                        <label><?php echo $this->__('Sort By') ?></label>
                        <select onchange="setLocation(this.value)" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sort By')) ?>">
                            <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                                <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                                    <?php echo $this->__($_order) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                        <?php if($this->getCurrentDirection() == 'desc'): ?>
                            <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" class="sort-by-switcher sort-by-switcher--desc" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Set Ascending Direction')) ?>"><?php echo $this->__('Set Ascending Direction') ?></a>
                        <?php else: ?>
                            <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" class="sort-by-switcher sort-by-switcher--asc" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Set Descending Direction')) ?>"><?php echo $this->__('Set Descending Direction') ?></a>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif; ?>

            <!-- items per page -->
            <div class="limiter">
                <label><?php echo $this->__('Show') ?></label>
                <select onchange="setLocation(this.value)" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Results per page')); ?>">
                <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                    <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                        <?php echo $this->__('%s Items',$_limit) ?>
                    </option>
                <?php endforeach; ?>
                </select>
            </div>
        </div>
    </div>
    <div class="bottom">
        <div class="pager">
            <?php echo $this->getPagerHtml() ?>
        </div>
    </div>
</div>
<?php endif ?>
