<?php
/**
 * CC form Template
 *
 * Description:
 * - Override vtpayment form template from base/default
 * - exchange expiration date and card verification number position
 * - reposition input fields
 * - change bank input from dropdown to radio
 *
 * @category    design
 * @package     default_icube
 * @copyright   Copyright (c) 2012 Icubeonline.com
 */
?>
<?php
$order=Mage::helper('checkout')->getQuote()->getData();
$grandTotal=$order['grand_total'];
?>
<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <div class="input-box">
            <?php $banks = unserialize(Mage::getStoreConfig('payment/vpaymentva/banks')); ?>
            <ul class="val-one-required">
                <?php $i=0; foreach($banks as $key => $bank): ?>
                <?php $i++; ?>
                <li>
                    <div class="v-fix">
                        <input type="radio" name="payment[vabank]" id="va_bank_<?php echo $key ?>" value="<?php echo $bank['bank']; ?>" <?php echo ($i==count($banks))? 'class="validate-one-required-by-name"':''; ?> />
                    </div>
                    <label for="va_bank_<?php echo $key ?>"><?php echo $bank['label']; ?></label>
                </li>
                <?php endforeach ?>
                <?php if(Mage::getStoreConfig('payment/vpaymentva/enablemandiribill')) : ?>
                    <li>
                        <div class="v-fix">
                            <input type="radio" name="payment[vabank]" id="va_bank_<?php echo Icube_Vpaymentva_Model_Vpaymentva::CODE_MANDIRI_BILLPAYMENT?>" value="<?php echo Icube_Vpaymentva_Model_Vpaymentva::CODE_MANDIRI_BILLPAYMENT?>" />
                        </div>
                        <label for="va_bank_<?php echo Icube_Vpaymentva_Model_Vpaymentva::CODE_MANDIRI_BILLPAYMENT?>"><?php echo $this->__('Mandiri Bill Payment'); ?></label>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </li>
</ul>
<?php if ($instructions = $this->getInstructions()): ?>
    <ul class="form-list checkout-agreements" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <li>
            <div class="<?php echo $this->getMethodCode() ?>-instructions-content agreement-content">
                <?php echo nl2br($instructions) ?>
            </div>
        </li>
    </ul>
<?php endif; ?>

<script type="text/javascript">
    var grand_total = <?php echo round($grandTotal); ?>;

    jQuery("input[name*='payment\[method\]']").change(function() {
        var sel_method = jQuery("input[name*='payment\[method\]']:checked").val();
        if(sel_method == 'vpaymentva') {
            jQuery("#payment-buttons-container").find(".button").prop('onclick',null).off('click').click(
                function savePaymentIns(){
                    payment.save();
                }
            );
        }
    });

    jQuery(document).ready(function() {
        jQuery("input[name*='payment\[method\]']").trigger("change");
    });
</script>