<div class="company-selection">
	<ul>
		<li><a href="javascript:void(0)" data-company="ace" class="ace"><?php echo $this->__('ACE') ?></a></li>
		<li><a href="javascript:void(0)" data-company="informa" class="informa"><?php echo $this->__('Informa') ?></a></li>
		<li><a href="javascript:void(0)" data-company="toyskingdom" class="toyskingdom"><?php echo $this->__('Toyskingdom') ?></a></li>
	</ul>
</div>