<?php
/** @var $this Icube_Rma_Block_Return_Create */

/*
 * Description:
 * - Change input for qty from input text to dropdown
 * - remove "penjelasan pengembalian"
 * - disable show/hide other reason field via showOtherOption()
 * - validate at least one checkbox item must be selected
 */
?>
<?php $_order =  $this->getOrder(); ?>
<?php $_data = $this->getFormData(); ?>


<form id="rma_create_form" method="post" name="rma_create_form" enctype="multipart/form-data">
    <div class="content-section">
        <div class="page-title title-buttons">
            <h1><?php echo $this->__('Pengembalian') ?></h1>
        </div>
        <h2><?php echo $this->__('Pengembalian') ?></h2>
        <h4><?php echo $this->__('Detail Order Anda') ?></h4>
        <ul class="desc-list order-detail">
            <li>
                <label><?php echo $this->__('Order Number') ?></label>
                <span class="value"><?php echo $_order->getIncrementId() ?></span>
            </li>
            <li class="hidden">
                <label><?php echo $this->__('Customer Name') ?></label>
                <span class="value"><?php echo $this->escapeHtml($_order->getCustomerName()) ?></span>
            </li>
            <li class="hidden">
                <label><?php echo $this->__('Order Shipping Address') ?></label>
                <span class="value"><?php echo $_order->getShippingAddress()->format('html') ?></span>
            </li>
            <li>
                <label><?php echo $this->__('Email') ?></label>
                <span class="value rma-email"><?php echo $_order->getCustomerEmail()?></span>
            </li>
            <li class="hidden">
                <label><?php echo Mage::helper('enterprise_rma')->getContactEmailLabel() ?></label>
                <span class="input-box value">
                     <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="customer_custom_email" id="email" title="Contact Email Address" class="input-text validate-email" value="<?php echo $this->getContactEmail()?>">
                </span>
            </li>
        </ul>
    </div>
    
    <?php $_items = $this->getItems(); ?>

    <?php 
        /* check whether has pickup items */
        $i = 0; 
        $hasPickupItems = false;
        foreach($_items as $_item) {
            if($_item->getDeliveryPickup() == 'pickup') {
                $hasPickupItems = true;
                break;
            }
        }
    ?>
    <?php if ($hasPickupItems): ?>
        <?php $currentPickupStore = 0; ?>
        <div class="content-section rma-pickup-items">        
        <!-- ITEMS WITH PICK UP DELIVERY METHOD -->
            <div class="rma-product-list">
                <?php foreach($_items as $_item): ?>
                    <?php if($_item->getDeliveryPickup() == 'pickup') : ?>
                        <?php if (strcmp($_item->getStoreCode(),$currentPickupStore)!==0) : ?>
                            <?php $currentPickupStore = $_item->getStoreCode(); ?>
                            <?php $store = Mage::getModel('pointofsale/pointofsale')->getCollection()->addFieldToFilter('store_code', $_item->getStoreCode())->getFirstItem(); ?>
                            <h4><?php echo $this->__('Produk di bawah ini hanya dapat dikembalikan dengan datang ke %s', $store->getName()) ?></h4>
                            <div class="store-info clearfix">
                                <div class="left">
                                    <b><?php echo $this->__('Tempat pengembalian') ?></b>
                                    <address>
                                        <?php echo $store->getName().'<br/>'; ?>
                                        <?php echo ($store->getAddressLine1())? $store->getAddressLine1().'<br/>': ''; ?>
                                        <?php echo ($store->getAddressLine2())? $store->getAddressLine2().'<br/>': ''; ?>
                                        <?php echo $store->getCity().', '. $store->getState().', '.$store->getPostalCode(); ?>
                                    </address>
                                </div>
                                <div class="left">
                                    <ul class="desc-list">
                                        <li>
                                            <label><strong>Phone</strong></label>
                                            <span class="value"><?php echo $store->getMainPhone(); ?></span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        <?php endif; ?>
                        <div class="item">
                            <table class="clearfix">
                                <tbody>
                                    <tr>
                                        <td></td>
                                        <td class="check"></td>
                                        <td class="product-detail-image">
                                            <div class="product-image">
                                                <img
                                                 src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(150); ?>"
                                                 alt="<?php echo $this->stripTags($this->getImageLabel($_item, 'small_image'), null, true) ?>" />
                                            </div>
                                        </td>
                                        <td class="product-details">
                                            <div class="product-name">
                                                <?php echo $_item->getName(); ?>
                                            </div>
                                            <div class="product-sku">
                                                <?php echo $this->__('SKU : %s',$_item->getSku()) ?>
                                            </div>
                                        </td>
                                        <td class="rma-detail">
                                            <p><?php echo $this->__('Harap membawa kartu identitas diri dan bukti pembayaran untuk melakukan penukaran produk') ?></p>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif ?>
 
    <?php 
        /* check whether has ordered items */
        $i = 0; 
        $hasDeliveredItems = false;
        foreach($_items as $_item) {
            if($_item->getDeliveryPickup() == 'delivery') {
                $hasDeliveredItems = true;
                break;
            }
        }
    ?>
    <?php if ($hasDeliveredItems): ?>
        <div class="content-section rma-delivered-items">
            <h4><?php echo $this->__('Produk di Bawah ini Dapat Anda Kembalikan Melalui Ekspedisi') ?></h4>
            <ul id="registrant_options" class="rma-product-list">
                <li class="no-display">&nbsp;</li>
           
        <?php $itemCount = 0; ?>
        <?php foreach($_items as $_item): ?>
        <?php if($_item->getDeliveryPickup() == 'delivery') : ?>

                    <?php $bundleID     = 0; ?>
                    <?php $firstId = $i = $productType = $availableQty = 0; ?>
                    <?php $html         = array(); ?>

                <li class="item">
                    <table>
                        <td>
                            <label for="items:item$itemCount" class="required hidden"><em>*</em><?php echo $this->__('Item') ?></label>
                        </td>
                        <td class="check">
                            <div class="input-box">
                                <?php if ($i == 0): ?>
                                    <?php
                                        $firstId = $_item->getId();
                                        $productType = $_item->getProductType();
                                        $availableQty = $this->getAvailableQty($_item);
                                        $i = 1;
                                    ?>
                                <?php endif; ?>
                                <?php if ($_item->getProductType() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE): ?>
                                    <?php $bundleID = $_item->getId(); ?>
                                <?php endif; ?>
                                <?php if (!$_item->getParentItemId() || $_item->getParentItemId() != $bundleID): ?>
                                    <input type="checkbox" name="items[<?php echo $itemCount; ?>][order_item_id]" value="<?php echo $_item->getId()?>" id="item:order_item_id<?php echo $itemCount; ?>_<?php echo $_item->getId() ?>" rel="<?php echo $_item->getProductType()?>_<?php echo $this->getAvailableQty($_item); ?>" onchange="deliveredItemChanged(this)"  class="validate-one-checkbox-item" />
                                <?php endif; ?>
                                <?php if ($_item->getParentItemId()!= null && $_item->getParentItemId() == $bundleID): ?>
                                    <?php if ($_item->getIsOrdered()): ?>
                                        <?php
                                            $html[$bundleID][] = array(
                                                $_item->getId(),
                                                $this->escapeHtml($_item->getName()),
                                                $this->getAvailableQty($_item),
                                                1
                                            );
                                        ?>
                                    <?php else: ?>
                                        <?php
                                            $html[$bundleID][] = array(
                                                $_item->getId(),
                                                $this->escapeHtml($_item->getName()),
                                                $this->getAvailableQty($_item),
                                                0
                                            );
                                        ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <!-- </select> -->
                            </div>
                        </td>
                        <td class="product-detail-image">
                            <div class="product-image">
                                <img
                                 src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(150); ?>"
                                 alt="<?php echo $this->stripTags($this->getImageLabel($_item, 'small_image'), null, true) ?>" />
                            </div>
                        </td>
                        <td class="product-details">
                            <div class="product-name">
                                <?php echo $this->escapeHtml($_item->getName())?>
                            </div>
                            <div class="product-sku">
                                <?php echo $this->__('SKU : %s',$_item->getSku()) ?>
                            </div>
                        </td>

                        <?php if(!empty($html)): ?>
                        <td>
                            <?php foreach($html as $bundleID=>$node): ?>
                                <div class="field">
                                    <label class="required"></label>
                                    <div class="input-box">
                                        <div id="radio:item<?php echo $itemCount; ?>_<?php echo $bundleID?>">
                                            <table class="data-table" id="return-items-table-<?php echo $bundleID?>">
                                                <colgroup>
                                                    <col width="10" />
                                                    <col width="143" />
                                                    <col width="82" />
                                                    <col width="65" />
                                                </colgroup>
                                                <thead>
                                                    <th colspan="2"><?php echo $this->__('Sub-items:') ?></th>
                                                    <th class="a-center"><?php echo $this->__('Remaining Qty:') ?></th>
                                                    <th class="a-center"><?php echo $this->__('Qty:') ?></th>
                                                </thead>
                                                <tbody>
                                            <?php foreach($node as $item): ?>
                                                <tr>
                                                    <td>
                                                    <?php if ($item[3]): ?>
                                                        <input type="checkbox" disabled />
                                                    <?php else: ?>
                                                        <input id="items[_index_][<?php echo $bundleID ?>][checkbox][item][<?php echo $item[0]?>]" onclick="showBundleInput(<?php echo $item[0]?>, <?php echo $bundleID?>, '_index_');" type="checkbox" value="<?php echo $item[0]?>" class="checkbox validate-one-checkbox-<?php echo $bundleID ?> change-container-classname" />
                                                    <?php endif; ?>
                                                    </td>
                                                    <td style="padding-left:0;padding-right:0;"><label for="items[_index_][<?php echo $bundleID ?>][checkbox][item][<?php echo $item[0]?>]" style="float: none !important;padding:0;margin:0;width:0;<?php echo ($item[3]) ? 'color:#999999;' : ''?>display:inline;"><?php echo $item[1]?></label></td>
                                                    <td class="a-center"><?php echo $item[2] ?></td>
                                                    <td width="65">
                                                        <?php if (!$item[3]): ?>
                                                            <input id="items[_index_][<?php echo $bundleID ?>][checkbox][qty][<?php echo $item[0]?>]" pattern="\d*" name="items[_index_][items][<?php echo $item[0]?>]" size="7" class="validate-greater-than-zero required-entry" style="display:none;" disabled="disabled"/>
                                                        <?php endif; ?>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                                </tbody>
                                            </table>
                                            <script type="text/javascript">decorateTable('return-items-table-<?php echo $bundleID?>');</script>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </td>
                        <?php endif; ?>
                        <td class="rma-input-detail">
                            <div class="field qty" id="qty_requested_block_<?php echo $itemCount; ?>">
                                <!-- <label for="items:qty_requested<?php //echo $itemCount; ?>" class="required"><em>*</em><?php //echo $this->__('Quantity To Return') ?></label>
                                <div class="input-box">
                                    <input type="text" pattern="\d*" class="input-text validate-greater-than-zero required-entry" value="" name="items[<?php //echo $itemCount; ?>][qty_requested]" id="items:qty_requested<?php //echo $itemCount; ?>" placeholder="<?php //echo $this->__('Quantity To Return') ?>">
                                </div> -->

                                <?php  
                                    $_totItemToReturn = $_item->getQtyShipped() - $_item->getQtyReturned();
                                ?>
                                <?php if ($_totItemToReturn > 0): ?>
                                    <select  pattern="\d*" class="required-entry" name="items[<?php echo $itemCount; ?>][qty_requested]" id="items:qty_requested<?php echo $itemCount; ?>">
                                        <option value=""><?php echo $this->__('Jumlah') ?></option>
                                        <?php for ($i = 1; $i <= $_totItemToReturn; $i++) {
                                            echo '<option value="'.$i.'">'.$i.'</option>';
                                        } ?>
                                    </select>
                                <?php else: ?>
                                    <p><?php echo $this->__('There is no item to be returned.') ?></p>
                                <?php endif ?>
                            </div>
                            <div class="field hidden" id="remaining_quantity_block_<?php echo $itemCount; ?>">
                                <label class="required"><?php echo $this->__('Remaining quantity:'); ?> </label>
                                <div class="input-box">
                                    <span id="remaining_quantity_<?php echo $itemCount; ?>"></span>
                                </div>
                            </div>

                            <?php foreach ($this->getAttributes() as $attribute):?>
                                <?php $attributeContent = $this->getAttributeHtml($attribute);?>
                                <?php $attributeCode = $attribute->getAttributeCode(); ?>
                                <?php $attributeContent = str_replace('_index_', $itemCount, $attributeContent); ?>
                                <?php if ($attributeContent): ?>
                                    <?php if ($attributeCode == 'reason_other'): ?>
                                        <div id="reason_other<?php echo $itemCount; ?>" class="field" style="display: none;"><?php echo $attributeContent;?></div>
                                    <?php else: ?>
                                        <div class="field <?php echo $attributeCode ?>"><?php echo $attributeContent;?></div>
                                    <?php endif; ?>
                                <?php endif;?>
                            <?php endforeach;?>
                        </td>
                    </table>
                </li>
                
            
                <?php $itemCount++; endif; ?>
            <?php endforeach; ?>
            </ul>
        </div>
    <?php endif ?>
    <?php /* end of: if has ordered items */ ?>

<script type="text/javascript">
//<![CDATA[
    function showOtherOption(value, index)
    {
        // if (value == 'other') {
        //     $('reason_other'+index).show();
        //     $('items:reason_other'+index).enable();
        // } else {
        //     $('reason_other'+index).hide();
        //     $('items:reason_other'+index).disable();
        // }
    }

    var liIndex         = 0;
    var regCount        = 0;
    var maxRegistrant   = 1000;
    var myTemplate      = new Template($('template_registrant').innerHTML, /(^|.|\r|\n)({{(\w+)}})/);
    $('template_registrant').remove();

    function showQuantity(type, index, qty) {
        if (type == '<?php echo Mage_Catalog_Model_Product_Type::TYPE_BUNDLE ?>') {
            if ($('qty_requested_block_'+index)) {
                $('qty_requested_block_'+index).hide();
            }
            if ($('remaining_quantity_block_'+index)) {
                $('remaining_quantity_block_'+index).hide();
            }
        } else {
            if ($('qty_requested_block_'+index)) {
                $('qty_requested_block_'+index).show();
            }
            if ($('remaining_quantity_block_'+index)) {
                $('remaining_quantity_block_'+index).show();
            }
            if ($('remaining_quantity_'+index)) {
                $('remaining_quantity_'+index).update(qty)
            }
        }
    }

    function showBundleInput(id, bid, index) {
        if ($('items['+index+']['+bid+'][checkbox][item]['+id+']').checked == true) {
            $('items['+index+']['+bid+'][checkbox][qty]['+id+']').show();
            $('items['+index+']['+bid+'][checkbox][qty]['+id+']').enable();
        } else {
            $('items['+index+']['+bid+'][checkbox][qty]['+id+']').hide();
            $('items['+index+']['+bid+'][checkbox][qty]['+id+']').disable();
        }
    }

    function enableBundle(index, bid) {
        $$('input[id^="items['+index+']['+bid+'][checkbox][item]["]').each(function(e) {
            e.enable();
        });
        $$('input[id^="items['+index+']['+bid+'][checkbox][qty]["]').each(function(e) {
            if(e.value) {
                e.enable();
            }
        });
    }

    function showBundle(index, itemId)
    {
        $$('div[id^="radio:item'+index+'_"]').each(function(e) {
            var curId = (e.id);
            if ($(curId)) {
                $(curId).up(1).hide();
            }
        });
        $$('input[id^="items['+index+']"]').each(function(e) {
           e.disable();
        });
        if ($('radio:item'+index+'_'+itemId)) {
            $('radio:item'+index+'_'+itemId).up(1).show();
            enableBundle(index, itemId);
        };

        if ($('item:order_item_id'+index+'_'+itemId)) {
            var typeQty = $('item:order_item_id'+index+'_'+itemId);
            typeQty = typeQty.readAttribute('rel');

            var position = typeQty.lastIndexOf('_');
            var type = typeQty.substring(0,position);
            var qty = typeQty.substr(position+1);

            showQuantity(type, index, qty)
        }
        return false;
    }

    function removeRegistrant(liIndex){
        $('items:item'+liIndex).up(2).remove();
        regCount--;
        return false;
    }
    function addRegistrant() {
        ul = $('registrant_options');
        var li = Element.extend(document.createElement("li"));
        // skipping first row
        if (liIndex != 0) {
            li.addClassName('add-row');
        }

        li.addClassName('fields');
        date_template = myTemplate.evaluate({});
        li.insert(date_template.gsub('_index_', liIndex));

        liIndex++;
        regCount++;

        ul.appendChild(li);

        showBundle((liIndex-1), <?php echo $firstId; ?>);
        showQuantity('<?php echo $productType?>', liIndex-1, <?php echo ($availableQty) ? $availableQty : 0?>);

        li.select('input, select').each(function(input) { //Thanks Andrey !
            if (input.tagName.toLowerCase() == 'select') {
                Event.observe(input, 'blur', dataForm.validator.onChange.bindAsEventListener(dataForm.validator));
            }
            if (input.type.toLowerCase() == 'radio' || input.type.toLowerCase() == 'checkbox') {
                Event.observe(input, 'click', dataForm.validator.onChange.bindAsEventListener(dataForm.validator));
            } else {
                Event.observe(input, 'change', dataForm.validator.onChange.bindAsEventListener(dataForm.validator));
            }
        });

        // skipping first row
        if (liIndex == 1) {
            $('btn-remove0').hide();
        }
    }

    // icube: enable/disable delivered order item
    function deliveredItemChanged(elm) {
        var _elm = jQuery(elm);

        if(_elm.is(':checked')) {
            _elm.closest('tr').find('.rma-input-detail input').prop("disabled", false);
            _elm.closest('tr').find('.rma-input-detail textarea').prop("disabled", false);
            _elm.closest('tr').find('.rma-input-detail select').prop("disabled", false);
            _elm.closest('tr').find('.rma-input-detail .select').removeClass("disabled");
            _elm.closest('tr').find('.rma-input-detail .validation-advice').hide();
            _elm.closest('tr').find('.rma-input-detail .validation-failed').removeClass('validation-failed');
            _elm.closest('tr').find('.rma-input-detail .not-required-entry').removeClass('not-required-entry').addClass('required-entry');
        }else{
            _elm.closest('tr').find('.rma-input-detail input').prop("disabled", true);
            _elm.closest('tr').find('.rma-input-detail textarea').prop("disabled", true);
            _elm.closest('tr').find('.rma-input-detail select').prop("disabled", true);
            _elm.closest('tr').find('.rma-input-detail .select').addClass("disabled");
            _elm.closest('tr').find('.rma-input-detail .validation-advice').hide();
            _elm.closest('tr').find('.rma-input-detail .validation-failed').removeClass('validation-failed');
            _elm.closest('tr').find('.rma-input-detail .required-entry').removeClass('required-entry').addClass('not-required-entry');
        }
    }
//]]>
</script>

    <div class="order-page"><dl class="order-info"></dl></div>

    <ul class="form-list hidden">
        <li class="fields last">
            <div class="field">
                <label for="rma_comment"><?php echo $this->__('Comments') ?></label>
                <div class="input-box">
                    <textarea id="rma_comment" style="height:6em;" cols="5" rows="3" name="rma_comment" class="input-text"><?php if ($_data): ?><?php echo $_data->getRmaComment(); ?><?php endif; ?></textarea>
                </div>
            </div>
        </li>
    </ul>


    <!-- IMAGES -->
    <div class="entry-edit entry-images content-section">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('rma-upload-image-instruction')->toHtml(); 
?>
        <div class="fieldset">
            <div class="hor-scroll">
                <ul class="form-list container image-list clearfix">
                </ul>
                <input type="button" class="add hidden" value="Add Image"/>
            </div>
        </div>
    </div>

    <script>
        jQuery(document).ready(function() {

            jQuery('.entry-images .add').click(function() {
                var wrapper = "<li class='wrapper-tr'>" +
                        "<div class='value'>"+
                            "<input type='file' name='images[]' onchange='getThumbnail(this)' accept='image/*' style='width:"+getImageWidth()+"px;height:"+getImageWidth()+"px'>"+
                            "<div class='thumb-wrapper' style='width:"+getImageWidth()+"px;height:"+getImageWidth()+"px'>"+
                            "<img class='thumb' src='<?php echo $this->getSkinUrl('images/icon-add_image.png') ?>' alt='Upload image' />"+
                            "</div>"
                        "</div>" +
                        "<span class='remove'>Remove</span>" +
                        "</li>";
                jQuery(wrapper).find('.remove').on('click', function() {
                    jQuery(this).parent('.wrapper-tr').remove();
                });
                jQuery(wrapper).appendTo('.entry-images .image-list');
            });
            jQuery('.image-list').on('click', 'span.remove', function() {
                    jQuery(this).parents('.wrapper-tr').remove();
            });
            jQuery('.entry-images .add').click();

            // icube: disable/enable rma input fields on document ready
            jQuery('#registrant_options input[type="checkbox"]').each(function() {
                deliveredItemChanged(this);
            });

            // icube: validate checkbox before submit
            jQuery('form[name="rma_create_form"]').on("submit", function(event) {
                
                event.preventDefault();

                var validateCheckbox = false;

                jQuery('#registrant_options input[type="checkbox"]').each(function() {

                    if(jQuery(this).is(':checked')) {
                        validateCheckbox = true;
                        return;
                    }
                });

                if (validateCheckbox) {
                    this.submit();
                }else{
                    alert("<?php echo $this->__('Please select the item you want to return.') ?>");
                }
            });
        });

        function getImageWidth() {

            /* img width base on screen width */
            if (jQuery(window).width() > 639) {
                var imageWidth = 85;
            }else{
                var parentWidth = jQuery('.entry-images.content-section').width();
                var margin = 10;
                var imageWidth = Math.floor((parentWidth - margin) / 2);
                            console.log(parentWidth);
                            console.log(imageWidth);
            }

            return imageWidth;
        }

        function getThumbnail(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    var image = new Image();
                    image.src = e.target.result;

                    image.onload = function() {

                        if (jQuery(window).width() > 480) {
                            jQuery(input).parent().find('.thumb').attr('src', this.src).width(getImageWidth()).height(getImageWidth());
                        }else{
                            jQuery('.image-list li').width(getImageWidth()).height(getImageWidth());
                            jQuery('.entry-images .value input').width(getImageWidth()).height(getImageWidth());
                            jQuery('.entry-images .thumb-wrapper').width(getImageWidth()).height(getImageWidth());

                            jQuery('.entry-images .image-list li:nth-child(even)').css('margin-left',5);
                            jQuery('.entry-images .image-list li:nth-child(odd)').css('margin-right',5);

                            jQuery(input).parent().find('.thumb').attr('src', this.src).width(getImageWidth()).height(getImageWidth());
                            jQuery('.entry-images .thumb-wrapper').width(getImageWidth()).height(getImageWidth());
                        }
                        jQuery('.entry-images .add').click();
                    };
                    
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>

    <div class="buttons-set form-buttons">
        <p class="back-link a-left"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button class="button" id="submit.save" title="<?php echo $this->quoteEscape($this->__('Save')) ?>"><span><span><?php echo $this->__('Submit') ?></span></span></button>
    </div>

</form>

<script type="text/javascript">
//<![CDATA[
function setFieldById(domId, value)
{
    x = $(domId);
    if (x != null) {
        x.setValue(value)
    };
}

function setItemFieldById(domId)
{
    x = $(domId);
    if (x != null) {
        x.selected = "selected";
    };
}

function setBundleFieldById(id, bundleID, index)
{
    showBundle(index, bundleID);
    showBundleInput(id, bundleID, index);
    showQuantity('bundle', index, 0);
}

var dataForm = new VarienForm('rma_create_form', true);
document.observe("dom:loaded", function() {
    <?php $i = 0; ?>
    <?php if ($_data): ?>
        <?php $formDataPost = $_data->getItems(); ?>
        <?php if (is_array($formDataPost)): ?>
            <?php foreach ($formDataPost as $item): ?>
                addRegistrant();
                <?php $parentId = 0; ?>
                <?php foreach ($item as $field => $value): ?>
                    <?php if ($field == 'order_item_id'): ?>
                        setFieldById('items:item[<?php echo $i;?>]', [<?php echo $value?>]);
                        showBundle(<?php echo $i;?>,<?php echo $value;?>);
                        setItemFieldById('item:order_item_id<?php echo $i;?>_<?php echo $value ?>');
                        <?php $parentId = $value; ?>
                    <?php elseif ($field == 'items'): ?>
                        <?php foreach($value as $id => $qty): ?>
                            setFieldById('items[<?php echo $i;?>][<?php echo $parentId;?>][checkbox][item][<?php echo $id;?>]', 'checked');
                            setFieldById('items[<?php echo $i;?>][<?php echo $parentId;?>][checkbox][qty][<?php echo $id;?>]', '<?php echo $qty;?>');
                            setBundleFieldById(<?php echo $id?>,<?php echo $parentId;?>,<?php echo $i;?>);
                            <?php unset($item['qty_requested']); ?>
                        <?php endforeach; ?>
                    <?php elseif ($field == 'qty_requested' && !empty($value)): ?>
                        setFieldById('items:<?php echo $field.$i?>', '<?php echo $value;?>');
                    <?php else: ?>
                        setFieldById('items:<?php echo $field.$i?>', '<?php echo $value;?>');
                        <?php if ($field == 'reason'): ?>
                            showOtherOption('<?php echo $value;?>', <?php echo $i ?>);
                        <?php endif; ?>
                    <?php endif; ?>

                <?php endforeach; ?>

            <?php $i++; ?>
            <?php endforeach; ?>
        <?php endif; ?>
    <?php endif; ?>

    <?php echo "liIndex = $i;\n"; ?>
    if (liIndex == 0) {
        addRegistrant();
    }

});

<?php if(!empty($html)): ?>
    <?php foreach($html as $key=>$value): ?>
    Validation.add('validate-one-checkbox-<?php echo $key?>', '<?php echo $this->jsQuoteEscape($this->__('Please select one of the options.')) ?>', function(value, entity) {
        var error = 1;
        $$('input[id*="][<?php echo $key?>][checkbox][item]["]').each(function(input) {
            if(input.checked == true) {
                error = 0;
            }
        });
        if(error == 0) {
            return true;
        } else {
            return false;
        }
    });
    <?php endforeach; ?>
<?php endif; ?>
//]]>
</script>
