<?php
/**
 * Layer State Template
 *
 * Description:
 * - Override beta/default
 * - Change block subtitle.
 * - Move Clear All link
 * 
 *
 * @category    design
 * @package     rwd_default
 * @copyright Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license http://www.magento.com/license/enterprise-edition
 */
?>
<?php
/**
 * Category layered navigation state
 *
 * @see Mage_Catalog_Block_Layer_State
 */
?>
<?php
$_filters = $this->getActiveFilters();
$_renderers = $this->getParentBlock()->getChild('state_renderers')->getSortedChildren();
?>
<?php if(!empty($_filters)): ?>
<div class="currently">
    <p class="block-subtitle">
        <?php echo $this->__('Filter by:') ?>
        <?php if ($this->getLayer()->getState()->getFilters()): ?>
            <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
        <?php endif; ?>
    </p>
    <ol>
    <?php foreach ($_filters as $_filter): ?>
        <?php
        $_rendered = false;
        foreach ($_renderers as $_rendererName):
            $_renderer = $this->getParentBlock()->getChild('state_renderers')->getChild($_rendererName);
            if (method_exists($_renderer, 'shouldRender') && $_renderer->shouldRender($_filter)):
                $_renderer->setFilter($_filter);
                echo $_renderer->toHtml();
                $_rendered = true;
                break;
            endif;
        endforeach;

        if (!$_rendered):
        ?>
        <li>
            <span class="label"><?php echo $this->__($_filter->getName()) ?>:</span> 
                <span class="value"><?php echo $this->stripTags($_filter->getLabel()) ?>

                <?php
                    $clearLinkUrl = $_filter->getClearLinkUrl();
                    if ($clearLinkUrl):
                ?>
                    <a  class="btn-previous" href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Previous')) ?>"><?php echo $this->__('Previous') ?></a>
                    <a  class="btn-remove" title="<?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>" href="<?php echo $clearLinkUrl ?>"><?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></a>
                <?php else: ?>
                    <a  class="btn-remove" href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove This Item')) ?>"><?php echo $this->__('Remove This Item') ?></a>
                <?php endif; ?>
            </span>
        </li>
        <?php endif; ?>
    <?php endforeach; ?>
    </ol>
</div>
<?php else: ?>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('.attributesplash-page-view .col-main .banners').removeClass('hidden');
    });
</script>
<?php endif; ?>