<?php
/**
 * Upsell Template
 *
 * Description:
 * - override rwd/enterprise
 * - Change block title
 *
 * @category    design
 * @package     rwd_enterprise
 * @copyright Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license http://www.magento.com/license/enterprise-edition
 */
/** @var $this Enterprise_TargetRule_Block_Catalog_Product_List_Upsell */
?>
<?php if ($this->hasItems()): ?>
<?php $_columnCount = $this->getColumnCount(); ?>
<div class="box-collateral box-up-sell">
    <div class="box-title">
        <h2><?php echo $this->__('Anda Mungkin Akan Menyukai') ?></h2>
    </div>
    <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col" id="upsell-product-table">
    <?php $i=0; foreach ($this->getItemCollection() as $_item): ?>
        <?php /*if ($i++ % $this->getColumnCount() == 0): ?>
            <ul class="products-grid">
        <?php endif */?>
        <li class="item<?php if (($i - 1) % $this->getColumnCount() == 0):?> first<?php elseif ($i % $this->getColumnCount() == 0):?> last<?php endif;?>">
            <?php
                $itemBlock = $this->getChild('catalog.product.upsell.item')->setItem($_item)->setPosition($i);
                echo $itemBlock->toHtml();
            ?>
        </li>
        <?php /*/if ($i % $this->getColumnCount() == 0 || $i == $this->getItemsCount()): ?>
            </ul>
        <?php endif*/ ?>
    <?php endforeach; ?>
    </ul>
    <?php /*
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    */ ?>
</div>
<?php endif ?>
