<?php
/**
 * Newsletter Subscription Form Template
 *
 * Description:
 * - override RWD/default
 * 
 */
?>

<div class="block block-subscribe">
    <div class="block-title">
        <?php echo $this->__('Subscribe Newsletter') ?>
    </div>
    <div class="block-content">
        <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
            <div class="form-subscribe-header">
                <label for="newsletter"><?php echo $this->__('Sign Up for Our Newsletter:') ?></label>
            </div>
            <div class="input-box">
               <input type="text" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="newsletter" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sign up for our newsletter')) ?>" class="input-text required-entry validate-email" placeholder="<?php echo $this->__('Enter your email...') ?>" />
            </div>
            <div class="actions">
                <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Subscribe')) ?>" class="button btn-orange"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
            </div>
        </form>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
</div>
