<?php
/**
 * Totals of Review Template
 *
 * Description:
 * - Coppied from beta/rwd
 * - Add checkbox for toggling form
 * 
 * @category    design
 * @package     rwd_enterprise
 * @copyright Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license http://www.magento.com/license/enterprise-edition
 */
?>
<?php
/**
 * @see Enterprise_GiftCardAccount_Block_Checkout_Cart_Giftcardaccount
 */
?>
<div class="giftcard">
    <h2><?php echo $this->__('Gift Cards') ?></h2>
    <div id="giftcard_balance_lookup"></div>
    <span id="gc-please-wait" class="please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Please wait, loading...') ?>
    </span>
    <form id="giftcard-form" action="<?php echo $this->getAddCartActionUrl(); ?>" method="post">
        <div class="clearfix">
            <div class="left">
                <div class="toggle-form">
                    <input type="checkbox" id="toggle-giftcard-form" />
                    <label for="toggle-giftcard-form"><?php echo $this->__('Punya Gift ?') ?></label>
                </div>
            </div>
            <div class="right">
                <div class="field-wrapper">
                    <input class="required-entry input-text" type="text" id="giftcard_code" name="giftcard_code" value="" />
                    <div class="button-wrapper">
                        <button class="button2" onclick="appyGiftCard(); return false;" type="button" value="<?php echo $this->__('Apply') ?>"><span><span><?php echo $this->__('Apply') ?></span></span></button>
                    </div>
                </div>
            </div>
        </div>
        <a class="check-gc-status" onclick="checkGiftCardStatus();" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Check Gift Card status and balance')) ?>"><span><span><?php echo $this->__('Check Gift Card status and balance') ?></span></span></a>
    </form>

    <script type="text/javascript">
    //<![CDATA[
    var giftcardForm = new VarienForm('giftcard-form');
    function checkGiftCardStatus()
    {
        if (giftcardForm.validator && !giftcardForm.validator.validate()) {
            return false;
        }
        new Ajax.Updater(
            'giftcard_balance_lookup',
            '<?php echo Mage::getUrl('enterprise_giftcardaccount/cart/quickCheck') ?>',
            {
                onCreate: function() { 
                    // $('gc-please-wait').show(); 
                    $('giftcard_balance_lookup').up().addClassName('loading')
                },
                onComplete: function() { 
                    $('gc-please-wait').hide(); 
                    $('giftcard_balance_lookup').up().removeClassName('loading')
                },
                parameters : {giftcard_code : $('giftcard_code').value}
            }
        );
    }

    function appyGiftCard()
    {
        if (giftcardForm.validator && !giftcardForm.validator.validate()) {
            return false;
        }

        new Ajax.Request(
            '<?php echo Mage::getUrl('customgiftcard/index/quickAddAjax') ?>',
            {
                onCreate: function() { 
                    // $('gc-please-wait').show(); 
                    $('giftcard_balance_lookup').up().addClassName('loading');
                },
                onComplete: function(result) { 
                    var response = JSON.parse(result.responseText);
                    var totalsShipping = $$('table.totals')[0];
                    var totalsPayment = $$('table.totals')[1];
                    var newTotals = response.totals;
                    if(newTotals != null){
                        totalsShipping.replace(newTotals);
                        totalsPayment.replace(newTotals);
                    }

                    document.getElementById('giftcard_code').value=""; 
                    $('giftcard_balance_lookup').update(response.message);
                    
                    // icube: add gc alert after totals in payment step
                    jQuery('.gc-alert-when-used').show();
                  
                    // $('gc-please-wait').hide(); 
                    $('giftcard_balance_lookup').up().removeClassName('loading');
                },
                parameters : {giftcard_code : $('giftcard_code').value}
            }
        );
    }

    function removeGiftCard(code)
    {
        new Ajax.Request(
            '<?php echo Mage::getUrl('customgiftcard/index/quickRemoveAjax') ?>',
            {
                onCreate: function() { 
                    // $('gc-please-wait').show(); 
                    jQuery('table.totals').addClass('loading');
                },
                onComplete: function(result) { 
                    var response = JSON.parse(result.responseText);
                    var totalsShipping = $$('table.totals')[0];
                    var totalsPayment = $$('table.totals')[1];
                    var newTotals = response.totals;
                    if(newTotals != null){
                        totalsShipping.replace(newTotals);
                        totalsPayment.replace(newTotals);
                    }

                    $('giftcard_balance_lookup').update(response.message);
                    
                    // icube: remove gc alert after totals on payment step if no more gc in current quote
                    new Ajax.Request(
                        '<?php echo Mage::getUrl('customgiftcard/index/hasGiftCard') ?>',
                        {
                            onComplete: function(result) { 
                                var response = JSON.parse(result.responseText);
                                
                                if (!response['result']) {
                                    jQuery('.gc-alert-when-used').hide();
                                };

                                jQuery('table.totals').removeClass('loading');
                            }
                        }
                    );

                    // $('gc-please-wait').hide(); 
                },
                parameters : {giftcard_code : code}
            }
        );
    }
    //]]>
    </script>
</div>
