<?php
/** 

 * Quickshop block 

 * 

 * @category Brainvire 

 * @package Brainvire_Quickshop

* @copyright Copyright (c) 2015 Brainvire Infotech Pvt Ltd
 
 * 
 */
?>

<script type="text/javascript">
//<![CDATA[
	if (typeof Brainvire == 'undefined') Brainvire = {};
	Brainvire.QuickShop = {
		BASE_URL : '<?php echo str_replace("index.php/","",$this->getUrl()) ?>',
		QS_FRM_TYPE : <?php echo Mage::getStoreConfig('quickshop/general/size_type');?>,
		QS_FRM_WIDTH : <?php echo Mage::getStoreConfig('quickshop/general/frame_width');?>,
		QS_FRM_HEIGHT : <?php echo Mage::getStoreConfig('quickshop/general/frame_height');?>,
		QS_IMG: '<?php echo $this->getSkinUrl('bv_quickshop/images/bvquickview.png'); ?>'
	};
	if(Brainvire.QuickShop.QS_FRM_TYPE == 0 ){
		Brainvire.QuickShop.QS_FRM_WIDTH = Brainvire.QuickShop.QS_FRM_WIDTH + "%";
		Brainvire.QuickShop.QS_FRM_HEIGHT = Brainvire.QuickShop.QS_FRM_HEIGHT + "%";
	}

//]]	
</script> 
