<?php
/**
 * Custom Login Template
 *
 * Description:
 * - coppied from rwd/persistent/form/login.phtml
 * - Remove the register part
 */
?>
<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>
<div class="account-login login-only">
    <div class="page-title">
        <h1>
            <?php echo $this->__('Login'); ?>
        </h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>

    <div class="content-section">
	    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" class="scaffold-form">
	        <?php echo $this->getBlockHtml('formkey'); ?>
	        <div class="col2-set">
	            <div class="col-1 registered-users">
	                <div class="content fieldset">
	                    <ul class="form-list">
	                        <li>
	                            <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
	                            <div class="input-box">
	                                <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->quoteEscape($this->__('Email Address')) ?>" />
	                            </div>
	                        </li>
	                        <li>
	                            <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
	                            <div class="input-box">
	                                <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->quoteEscape($this->__('Password')) ?>" />
	                            </div>
	                        </li>
	                        <?php echo $this->getChildHtml('form.additional.info'); ?>
	                        <li>
	                            <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
	                        </li>
	                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
	                    </ul>
	                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
	                </div>
	                <div class="buttons-set">
	                    <button type="submit" class="button" title="<?php echo $this->quoteEscape($this->__('Login')) ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
	                </div>
	            </div>
	        </div>
	        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
	            <input name="context" type="hidden" value="checkout" />
	        <?php endif; ?>
	    </form>
	    <script type="text/javascript">
	    //<![CDATA[
	        var dataForm = new VarienForm('login-form', true);
	    //]]>
	    </script>
	</div>
</div>
