<?php
/**
 * Address within Dashboard template
 *
 * Description:
 * - Override rwd/default
 * - Move edit link placement
 *
 *
 * @category    design
 * @package     rwd_default
 * @copyright Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license http://www.magento.com/license/enterprise-edition
 */
?>
<div class="box-account box-info">
    <div class="box-head">
        <h2><?php echo $this->__('Address Book') ?></h2>
        <a href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a>
    </div>
    <div class="col2-set">
        <div class="col-1">
            <div class="box">
                <div class="box-title">
                    <h3><?php echo $this->__('Default Billing Address') ?></h3>
                </div>
                <div class="box-content">
                    <address><?php echo $this->getPrimaryBillingAddressHtml() ?></address>
                    <div class="actions">
                        <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>" class="edit flaticon-pencil124"><?php echo $this->__('Edit') ?></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-2">
            <div class="box">
                <div class="box-title">
                    <h3><?php echo $this->__('Default Shipping Address') ?></h3>
                </div>
                <div class="box-content">
                    <address><?php echo $this->getPrimaryShippingAddressHtml() ?></address>
                    <div class="actions">
                        <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>" class="edit flaticon-pencil124"><?php echo $this->__('Edit') ?></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
