<?php
/**
 * Account Info Dashboard template
 *
 * Description:
 * - Override base/default
 * - Move edit link placement
 *
 *
 * @category    design
 * @package     base_default
 * @copyright Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license http://www.magento.com/license/enterprise-edition
 */
?>
<div class="col2-set">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h3><?php echo $this->__('Contact Information') ?></h3>
            </div>
            <div class="box-content">
                <p>
                    <?php echo $this->escapeHtml($this->getCustomer()->getName()) ?><br />
                    <?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?><br />
                    <a href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('Change Password') ?></a>
                </p>
                <div class="actions">
                    <a href="<?php echo $this->getUrl('customer/account/edit') ?>" class="edit flaticon-pencil124"><?php echo $this->__('Edit') ?></a>
                </div>
            </div>
        </div>
    </div>
    <?php if( $this->isNewsletterEnabled() ): ?>
    <div class="col-2">
        <div class="box">
            <div class="box-title">
                <h3><?php echo $this->__('Newsletters') ?></h3>
            </div>
            <div class="box-content">
                <p>
                    <?php if( $this->getIsSubscribed() ): ?>
                        <?php echo $this->__("You are currently subscribed to 'General Subscription'.") ?>
                    <?php else: ?>
                        <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
                    <?php endif; ?>
                </p>
                <div class="actions">
                    <a href="<?php echo $this->getUrl('newsletter/manage') ?>" class="edit flaticon-pencil124"><?php echo $this->__('Edit') ?></a>
                </div>
            </div>
        </div>
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('customer.account.dashboard.info.extra')?>
    </div>
    <?php endif; ?>
</div>
