<?php
/**
 * CC form Template
 *
 * Description:
 * - Override vtpayment form template from base/default
 * - exchange expiration date and card verification number position
 * - custom cc type
 *
 * @category    design
 * @package     default_icube
 * @copyright   Copyright (c) 2012 Icubeonline.com
 */
?>
<?php
$limitTotal=Mage::getStoreConfig('payment/klikpay/total_amount');
$order=Mage::helper('checkout')->getQuote()->getData();
$grandTotal=$order['grand_total'];
?>
<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type card-number" value="" autocomplete="off" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="card-expiry-month month validate-cc-exp required-entry">
                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                    <?php foreach ($this->getCcMonths() as $k=>$v):
                        $monthFrm=sprintf("%02d", $k);
                        ?>
                        <option value="<?php echo $monthFrm?$monthFrm:'' ?>"<?php if($monthFrm==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="card-expiry-year year required-entry">
                    <option value="2015"<?php if("2015"==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo "2015" ?></option>
                    <?php foreach ($this->getCcYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
                <input id="token_id" name="payment[token_id]" type="hidden" />
            </div>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_cid" class="required" style="font-size: smaller"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="password" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn card-cvv" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
            </div>
            <span href="#" class="tooltip cvv-what-is-this"></span>
        </div>
    </li>
    <?php if($this->getPromoProgramCollection()->getSize() > 0) { ?>
        <li>
            <label><?php echo $this->__('Promo') ?></label>
            <div class="input-box">
                <?php echo $this->getPromoProgramHtml(); ?>
            </div>
        </li>
    <?php } ?>
</ul>

<!-- This is for checking if BIN number is correct by Sutrisno on April Mop 2016 -->
<script type="text/javascript">
var cnum;
jQuery(document).ready(function(){
    jQuery("#<?php echo $_code ?>_cc_number").change(function(){
       cnum = jQuery("#<?php echo $_code ?>_cc_number").val();
       cnum = cnum.replace(/\s+/g, '');
       jQuery.ajax({
            type: "POST",
            url: "<?php echo Mage::getUrl('vpayment/payment/binchecking',array('_secure'=>Mage::app()->getStore()->isCurrentlySecure())) ?>",
            data: {
                "ccnum": cnum }, success: function(result){
                    if (result == "false"){ 
                        jQuery("#<?php echo $_code ?>_cc_number").val("");
                        alert ('Maaf, Hanya dapat menggunakan Kartu Kredit BNI saja');
                     }
                    else {}
                
              }
            });
    });
});
</script>

<!-- This is for mandiri promo by Sutrisno on May Day-->
<script type="text/javascript">
var cnum;
jQuery(document).ready(function(){
    jQuery("#<?php echo $_code ?>_cc_number").change(function(){
       cnum = jQuery("#<?php echo $_code ?>_cc_number").val();
       cnum = cnum.replace(/\s+/g, '');
       jQuery.ajax({
            type: "POST",
            url: "<?php echo Mage::getUrl('vpayment/payment/manchecking',array('_secure'=>Mage::app()->getStore()->isCurrentlySecure())) ?>",
            data: {
                "ccnum": cnum }, success: function(result){
                //do nothing
              }
            });
    });
});
</script>

<script type="text/javascript">
    var promo_code;
    var grand_total = <?php echo round($grandTotal); ?>;
    jQuery("input:radio[name='payment[promo]']").click(function() {
        promo_code = jQuery(this).val();
    });
    jQuery("input[name*='payment\[promo\]']").change(function() {
        jQuery("#payment-buttons-container").find(".button").prop('disabled', true);
        jQuery("input[name*='payment\[promo\]']").prop('disabled', true);
        jQuery.ajax({
            type: "POST",
            url: "<?php echo Mage::getUrl('vpayment/payment/getquotegrandtotal',array('_secure'=>Mage::app()->getStore()->isCurrentlySecure())) ?>",
            data: {
                "id": "<?php echo $order['entity_id']?>",
                "promo_code": promo_code
            },
            success: function(data){
                jQuery.ajax({
                    type: "POST",
                    url: "<?php echo Mage::getUrl('vpayment/payment/calculatequoteajax',array('_secure'=>Mage::app()->getStore()->isCurrentlySecure())) ?>",
                    data: {
                        "id": "<?php echo $order['entity_id']?>"
                    },
                    success: function(data){
                        var limitTotal=<?php if($limitTotal=='' or $limitTotal==0){$limitTotal=500000;}; echo round($limitTotal); ?>;

                        var response = jQuery.parseJSON(data);
                        grand_total = response.gt;

                        var totalsShipping = $$('table.totals')[0];
                        var totalsPayment = $$('table.totals')[1];
                        var newTotals = response.totals;
                        if(newTotals != null){
                            totalsShipping.replace(newTotals);
                            totalsPayment.replace(newTotals);
                        }
                        jQuery("#payment-buttons-container").find(".button").prop('disabled', false);
                        jQuery("input[name*='payment\[promo\]']").prop('disabled', false);
                    }
                })
            },
            error: function(data){
                jQuery("#payment-buttons-container").find(".button").prop('disabled', false);
                jQuery("input[name*='payment\[promo\]']").prop('disabled', false);
            },
            timeout: function(data){
                jQuery("#payment-buttons-container").find(".button").prop('disabled', false);
                jQuery("input[name*='payment\[promo\]']").prop('disabled', false);
            }
        })
    });
    jQuery("input[name*='payment\[method\]']").change(function() {
        var sel_method = jQuery("input[name*='payment\[method\]']:checked").val();
        if(sel_method == 'vpayment') {
            jQuery("#payment-buttons-container").find(".button").prop('onclick',null).off('click').click(
                function savePayment(){
                    var win;
                    Veritrans.client_key = "<?php echo Mage::getStoreConfig('payment/vpayment/client');?>"; //add client-key from veritrans
                    var secure = false;
                    if('1' == '<?php echo Mage::getStoreConfig('payment/vpayment/secure_enable'); ?>') {
                        secure = true;
                    }
                    <?php if(Mage::getStoreConfig('payment/vpayment/authorize_only') == 1) { ?>
                    function _cardSet(){
                        return {
                            "card_number" : $("vpayment_cc_number").value,
                            "card_exp_month": $("vpayment_expiration").value,
                            "card_exp_year" : $("vpayment_expiration_yr").value,
                            "card_cvv" : $("vpayment_cc_cid").value,
                            "secure"        : secure,
                            "gross_amount"  : grand_total,
                            "type" : "authorize"
                        }
                    };
                    <?php } else { ?>
                    function _cardSet(){
                        return {
                            "card_number" : $("vpayment_cc_number").value,
                            "card_exp_month": $("vpayment_expiration").value,
                            "card_exp_year" : $("vpayment_expiration_yr").value,
                            "card_cvv" : $("vpayment_cc_cid").value,
                            "secure"        : secure,
                            "gross_amount"  : grand_total
                        }
                    };
                    <?php } ?>
                    function _success(d){//alert('5:'+JSON.stringify(d));
                        if (d.redirect_url) {
                            if(secure) {
                                jQuery.fancybox.open({
                                    href: d.redirect_url,
                                    type: 'iframe',
                                    autoSize: true,
                                    closeBtn: true
                                });
        //                        win = window.open(d.redirect_url, '_blank');
        //                        win.focus();
                            }
                        } else if(d.status_code=='200'){
                            if(secure) {
                                jQuery.fancybox.close();
        //                        win.close();
                            }
                            $('token_id').value = d.token_id; // store token data in input #token_id
                            var timeout = setTimeout(function() {
                                if(d.status_code=='200'){
                                    payment.save();
                                    if($("vpayment_cc_number")) {
                                        $("vpayment_cc_cid").value = '';
                                        $("vpayment_cc_number").value = '';
                                    }
                                }else{
                                    _error(d);
                                }
                            }, 2000);
                        }else{
                            _error(d);
                        }
                    };
                    function _error(d){//alert('12:'+JSON.stringify(d));
                        mytext=d.status_message.replace('[','');
                        mytext=mytext.replace(']','');
                        //alert('error:'+JSON.stringify(d, null, 4));
                        alert('error:'+mytext);
                    };

                    function setSession(res){
                        if(res){
                            //jQuery('#stat').val(1);
                        }else{
                            //jQuery('#stat').val(0);
                        }
                    }
                    if(payment.currentMethod=='vpayment'){
                        //jQuery('span#payment-please-wait').css('display','block');
                        Veritrans.token(_cardSet, _success);
                    }else{
                        payment.save();
                    }
                }
            );
        }
    });
    jQuery(document).ready(function() {
        jQuery("input[name*='payment\[method\]']").trigger("change");

        /* custom cc type */
        jQuery('input.vpayment-custom_cc_type, input.vpayment-custom_cc_type+label').on('click', function() {
            var value = jQuery(this).val();
            jQuery('#vpayment_cc_type').val(value);
        });
    });
</script>