<?php
/**
 * Social buttons on Checkout Template
 *
 * Description:
 * - override RWD/default
 * - override Inchoo Social Connect ext
 * 
* @category Inchoo
* @package SocialConnect
* @author Marko Martinović <marko.martinovic@inchoo.net>
* @copyright Copyright (c) Inchoo (http://inchoo.net/)
* @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
*/
?>
<div class="inchoo-socialconnect-checkout">
    <?php echo $this->getChildHtml('inchoo_socialconnect_checkout_facebook_button')?>
    <?php echo $this->getChildHtml('inchoo_socialconnect_checkout_google_button')?>
    <?php echo $this->getChildHtml('inchoo_socialconnect_checkout_twitter_button')?>
</div>
