<?php
/**
 * Social buttons on Register Template
 *
 * Description:
 * - override RWD/default
 * - override Inchoo Social Connect ext
 * 
* @category Inchoo
* @package SocialConnect
* @author Marko Martinović <marko.martinovic@inchoo.net>
* @copyright Copyright (c) Inchoo (http://inchoo.net/)
* @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
*/
?>

<div class="inchoo-socialconnect-register">   
<p><strong><?php echo $this->__('OR REGISTER WITH YOUR SOCIAL MEDIA ACCOUNT') ?></strong></p>
    <?php if($this->_facebookEnabled()): ?>
    <div class="inchoo-socialconnect-register-facebook">
        <?php echo $this->getChildHtml('inchoo_socialconnect_checkout_facebook_button')?>
    </div>
    <?php endif; ?>
    <?php if($this->_googleEnabled()): ?>
    <div class="inchoo-socialconnect-register-google">
        <?php echo $this->getChildHtml('inchoo_socialconnect_checkout_google_button')?>
    </div>
    <?php endif; ?>
    <?php if($this->_twitterEnabled()): ?>
    <div class="inchoo-socialconnect-register-twitter">
        <?php echo $this->getChildHtml('inchoo_socialconnect_checkout_twitter_button')?>
    </div>
    <?php endif; ?>
</div>