<script>
   
    
    url='<?php echo $this->getUrl('*/*/loadfile', array('profile_id' => $this->getProfile_id())) ?>';
    
   

</script>
<div class='entry-edit'>
    <div class="entry-edit-head"><h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('File mapping'); ?></h4></div>
    <div class="fieldset">
       
     
        <div class="main-box">
            <table id="import-preview" border='0' bgcolor="white" cellpadding="0" cellspacing="0" >
                <thead>
                    
                </thead>
                <tbody>
                  
                </tbody>
            </table>
            <div id="import-error"></div>

        </div>
    </div>
</div>
