<?php
/**
 * Improved Layered Nav State Template
 *
 * Description:
 * - Override rwd/enterprise --> default amshopbby template
 */
?>
<?php $_filters = $this->getActiveFilters() ?>
<?php $_removeTxt = Mage::helper('catalog')->__('Remove This Item') ?>

<?php if (!empty($_filters)): ?>
<div class="currently">
    <p class="block-subtitle"><?php echo Mage::helper('catalog')->__('Shopping by') ?></p>
    <ol>
    <?php foreach ($_filters as $_filter): ?>
        <li>
            <span class="label"><?php echo Mage::helper('catalog')->__($_filter->getName()) ?>:</span>
            <?php if ($_filter->hasData('children')): ?>
                <?php foreach ($_filter->getData('children') as $child): ?>
                    <span class="value">
                        <?php echo $child['label'] ?>
                        <a href="<?php echo $child['url'] ?>" class="btn-remove"><?php echo $_removeTxt ?></a>
                    </span>
                <?php endforeach ?>
            <?php else: ?>
            <span class="value">
                <?php echo $_filter->getLabel() ?>
                <a href="<?php echo $_filter->getRemoveUrl() ?>" class="btn-remove" title="<?php echo $_removeTxt ?>"><?php echo $_removeTxt ?></a>
            </span>
            <?php endif ?>
        </li>
    <?php endforeach; ?>
    </ol>
    <?php if (Mage::helper('amshopby')->isVersionLessThan(1, 7)): ?>
    <div class="actions"><a href="<?php echo Mage::helper('amshopby/url')->getFullUrl(array(), 1) ?>"><?php echo Mage::helper('catalog')->__('Clear All') ?></a></div>
    <?php endif; ?>
</div>
<?php endif; ?>
