<?php

class Wyomind_Pointofsale_Block_Adminhtml_Manage_Edit_Tab_Informations extends Mage_Adminhtml_Block_Widget_Form {

    protected function _prepareForm() {
        $form = new Varien_Data_Form();

        $this->setForm($form);

        $fieldset = $form->addFieldset('informations_store', array('legend' => Mage::helper('pointofsale')->__('General Informations')));

        $model = Mage::getModel('pointofsale/pointofsale');
        $model->load($this->getRequest()->getParam('place_id'));



        if ($this->getRequest()->getParam('place_id')) {

            $fieldset->addField('place_id', 'hidden', array(
                'name' => 'place_id',
            ));
        }

        //ICUBE Custom
        $fieldset->addField('company_id', 'select', array(
            'label' => Mage::helper('pointofsale')->__('Company ID'),
            'name' => 'company_id',
            'values' => array(
                array(
                    'value' => NULL,
                    'label' => Mage::helper('pointofsale')->__(''),
                ),
                array(
                    'value' => 'HCI',
                    'label' => Mage::helper('pointofsale')->__('Infoma (HCI)'),
                ),
                array(
                    'value' => 'AHI',
                    'label' => Mage::helper('pointofsale')->__('ACE (AHI)'),
                ),
                array(
                    'value' => 'TGI',
                    'label' => Mage::helper('pointofsale')->__('Toys Kingdom (TGI)'),
                ),
            ),
        ));
        //End of ICUBE Custom

        $fieldset->addField('store_code', 'text', array(
            'label' => Mage::helper('pointofsale')->__('Code (internal use)'),
            'name' => 'store_code',
            'class' => 'required-entry',
            'required' => true,
        ));

        $fieldset->addField('name', 'text', array(
            'label' => Mage::helper('pointofsale')->__('Name'),
            'name' => 'name',
            'class' => 'required-entry',
            'required' => true,
        ));


        $fieldset->addField('status', 'select', array(
            'label' => Mage::helper('pointofsale')->__('Type of display'),
            'name' => 'status',
            'values' => array(
                array(
                    'value' => 0,
                    'label' => Mage::helper('pointofsale')->__('Warehouse (not visible on the Gmap/checkout)'),
                ),
                array(
                    'value' => 1,
                    'label' => Mage::helper('pointofsale')->__('Point of Sales (visible on the Gmap/checkout)'),
                ),
            ),
        ));
        $fieldset->addField('position', 'text', array(
            'label' => Mage::helper('pointofsale')->__('Order of display'),
            'name' => 'position',
            'class' => 'required-entry validate-number',
            'required' => true,
        ));



        $fieldset->addField('latitude', 'text', array(
            'label' => Mage::helper('pointofsale')->__('Latitude'),
            'class' => 'validate-number',
            'name' => 'latitude',
            'class' => 'required-entry validate-number',
            'required' => true,
        ));

        $fieldset->addField('longitude', 'text', array(
        'label' => Mage::helper('pointofsale')->__('Longitude'),
        'class' => 'validate-number',
        'name' => 'longitude',
        'class' => 'required-entry validate-number',
        'required' => true,
        'after_element_html' => '  
                <style type="text/css">
                div#map {
                       
                        background: #efefef no-repeat 50% 50% url(\'data:image / gif;base64, R0lGODlhIAAgAMYAACxivCyybJy6/CSKjKzexFyS9Nzm/Hy2vCx2pOz69FSOvHTKnDx69CSedLTO/ISq9Nzy5ES6fPz6/ESC9CxurNTu3Gya9Iyy/ITSpCSqZOzy/CSafCSGlPT2/MTW/OTu/JS6/DSybKzC/CSShLTizCR+nFSK9HzOpER+9CSmbOTy7Ey6fEyC9DRutHSe9JSy/PT69CxmtKTC/CSOjKzixGSS9OTq/HTOnDx+9CyefLzS/Iyu/Nzy7Pz+/NTu5Gye9ITSrCSuZMza/DS2dCx+nFSO9Ey+hEyG9DRyvJS2/PT6/P7+/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQJBgBLACwAAAAAIAAgAAAH/oBLgoOEHQ4PBSgMMUgKByQwhJKTgzYPigyZDACcABQ5JxCUlEpJOJqonZwxA0FAEqODHzWotTGqnK0RPLEGR7W1uJ0jQSE+lB+/wKnCADEpxbyESrTLzM0lGUERsIMC1rbNnA1BrrKn4JrinCXlQaJLO+nXzTHaQQtLShPz6usAG+4l0NFP0611HNwRuFAw0z8ACNwtsNBw0z8KQbRFUFbwYQx3QTAVPLjuXhB+DR8CyFjOREWPICmm/PexXASGDUliu7fAw8t/CbXRkMBi5rqA5VQsSWK0Hk9BGkSm04mrXbljgmR0XEcuyAlCEmSmW0fEZiRCGgrME/dMmzRJODZcgqPKiVgArJQ0uADXTBe8WBJkoAyGqxUGJbEkdRDA0WGnTwv+JpYkQQgIF0WOxGjhiECCxIEAACH5BAkGAEcALAAAAAAgACAAhixivCyybJy6/CSKjKzixNzm/Cx6pFyS9Iyy/Oz69Dx69FSK9HTKnLTO/CSmbNzy5ISq9ES6fPz6/ESC9CxurDR+rGya9ITSpOzy/NTu3JS6/PT2/MTW/EyulOTu/CxqtDSybKzC/CSWfCSClJSy/ER+9HzOpOTy7Ey6fEyC9HSe9PT69CxmvKTC/CSOhLTizOTq/GSS9Dx+9FSO9HTOnLzS/CSuZNzy7Iyu/Pz+/CxyrDx+rGye9ITSrNTu5Mza/FSulDS2dCSGlJS2/Ey+hEyG9PT6/P7+/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf+gEeCg4QbDRAHJQofO0AmLyuEkpODMBCKCpkKAJwuNgEmD5SURkMymqicnCI2rT0So4MeMai1LKofDq02ETexBUW1taqcI7ufPpQewcKpxAC6uyC+hEa0zai3xAPHvEaEAtjDzzrdNj2yp+Kaz5zR0TaiRzjrzs+s3QxHRhP1mtrEjJlLUMMfu3Yj3u0igMBgpnYAKJizwcCCw03tPhyLFoGZQYDEWsFrhckgRAATbfRzeNIGvGgLLracaNEhSE4aRe6K0JBlO4nmGHCQifBlKwISUvh8JrDbiSNDbLbDB0/fEQwl10Ec2SrDoBYmyW20QYOQhJpan3E7FiQSIQw/B+qBZGFUniQYMcUx7eZ1FAYVenHBC2J3lIQWK8et2kXDbaxBGwR4zKTNE8W+jydJ+KFBxYwiLCp0oEEgweNAACH5BAkGAEcALAAAAAAgACAAhixivCyybJy6/CSOhKzixNzm/Iyy/FyS9Cx6nOz69Dx69FSK9HTKnES6fLTO/CSidNzy5ISq9Pz6/ESC9CxurGya9ITSpCSqZOzy/NTu3JS6/CSClPT2/FS+hMTW/OTu/DSqfCxmtDSybKzC/JSy/ER+9HzOpEy6fOTy7EyC9HSe9CyqdPT69KTC/CSafLTizOTq/GSS9Cx6pDx+9FSO9HTOnLzS/Nzy7Iyu/Pz+/CxyrGye9ITSrCSuZNTu5CSGlMza/CxmvDS2dJS2/Ey+hEyG9PT6/P7+/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf+gEeCg4QcDhEHJQo6IB0mLyyEkpODMBGKCpkKAAg9ngE1N5SURkMzmqgAAA8XPa09PBKjgx8xqLeqP56ung2iowVFt7gAOq+7PQE+lB/Cw6mqrdK8QhCSRrbP0AAuyLsXDUaEAtq3IaoDntO7FrSn5ZqqALrIxz3WRzjw2wjr6p4MjhiZsE/TuWLfeP1LYKNgPFUU7P3zRMCAw0zyQvyTeIFBhYubVGmsp7BHA2cODwLwN7EHJofyVm701oPgxZgcSy4AGXMmyY8XD4bI+aqBxZsifSKr4YEnRJrrCEhIgbTYNIk9UBwZElTVBqI9Ah7B8BKevK+8JGYY1AImOqhRrmoQkgDUrKpuLIVEIoThwD559qbhkwRjZ7lzOtIiWzsKg4pyubxdqDZLkIQWNomxUlhjb2VBHASgxNhvFwPGnyVJAKJBBY0iOlYQYUDg16hAACH5BAkGADkALAAAAAAgACAAhTx69JSy/CSuZKzixNzm/ISq9FyS9Oz69LTO/ES6fEyG9HTKnNzy5KTC/Pz6/EyC9DSybMza/Gya9ITSpOzy/ESC9JS6/PT2/FS+hOTu/ER+9CyubIyy/MTW/Ey6fFSO9HzOpOTy7NTu3HSe9PT69Dx+9JS2/LTizOTq/Iyu/GSS9LzS/FSK9HTOnNzy7KzC/Pz+/DS2dGye9ITSrJy6/CyybEy+hNTu5PT6/P7+/gAAAAAAAAAAAAAAAAAAAAAAAAbkwJxwSLwgCgYNoAbBgE4konQ6RBWUgCxAwOVuWi4qFWcqac/dtGDmEA8zqrNcnU6ExQSFfE7v1m5UGXp7aH1dEHdDOHGEhYZcCThENI18j1wzb2aVWpdpDEIpnI6eCzk4FaOdnl0HK6qrrAIDHLBZslwLErZbuDGDsLgCG1jBwqm2wgIsvMq7yb610LILHc24Aw4P06whOSbclxhCFMWcuIBCDcalRA7P554bbUQUBqOs6VIozJWeIm4ojPBnaIM+MQ4aILOkZsEFN1Iu0AB2Sw0GAhARRrAw4oOCDRsSLBjgzU0QACH5BAkGAEsALAAAAAAgACAAhhySVJSy/CSuZEyC9KzixCyCtNzm/ISq9Oz69CSKhFyS9LTO/ES6fDR+3ByObHTKnNzy5ER+9KTC/Pz6/DSybFSO5Mza/Gya9DyC5ITSpOzy/BySZJS6/PT2/CyGnFS+hDx67CyWbOTu/ByWVCyubIyy/MTW/Ey6fCSOdHzOpOTy7FSK9NTu3HSe9PT69Dx+9BySXJS2/EyG9LTizDR+1OTq/Iyu/CSKjGSS9LzS/HTOnNzy7ESC9KzC/Pz+/DS2dGye9ITSrJy6/CyGpDx69CyybEy+hCSOfFSO9NTu5PT6/P7+/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf+gEuCg4QdCwcKGChFFB8pMy6EkpODNQcRRJk3IwKdnSQ6O5SUSjEvmZkYAACerQJBE6ODIjioqEMAnK6eDKKjBjK2qA6ru61FSZQiwcKZMCOsxp4UvoNKtc1ENNC60p0MSoRC2ZkF0NHenUGzp+QeI9DprRCCNuSauejyD0tKPPdEjnBz1a1bJwQ5ABJxcE5eKwIlFG7I59DTgwsKn+Wq2OkHs3v59MkjgQlgrnjpDP4zObBVwV0rFIbk2AkjwGcoKzKICHBiTocPTChkuJEjgQkDABL7KU/FkhgANxXt9LIVvyUaSmYb0rAii0ES7pljKu2qoAk2m22b6o1COEJBGhRkA0FRHr1JNWI2Wyrv6ygNLZpx1Vfwx11ZEySszNSgmDEdb2UN6iDkYwKDnR74lTxpgoUYQCps+PaAQDVKgQAAIfkECQYATAAsAAAAACAAIACGHJJUlLL8JK5kTIL0rOLELIas3Ob8hKr07Pr0JIqMXJbcPHrstM78RLp8dMqc3PLkJI50pML8VI70/Pr8PJ6ENLJszNr8NILELJKERIL0hNKk7PL8HJJklLr89Pb8LIacbKLURH70VL6E5O78HJZULK5sVIr0LIK8jLL8PH70xNb8TLp8fM6k5PLsZJL01O7c9Pr0LIqcHJJclLb8TIb0tOLMLIa05Or8jK78bJr0PHr0vNL8dM6c3PLsJI58rML8XJL0/P78NLZ0NILMhNKsnLr8LIakbJ70LLJsTL6E1O7k9Pr8/v7+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/6ATIKDhB4MBwoYMkgVIiw1MISSk4M3ByE6JwAkAAKeniU8PZSUSzMpOjpDm5ufrgJEE6SDIy6pOgsyrCSvrg2jpAY0tzofnJydvZ9ISpQjw7e5x5zKrhXAg0u2xDa7rdWfDUuERcSpEN7J4J5EtKjEC97U658Pgjjmmce79J8OTEsy5DMiT50nXgdfIdiRT0eCfcf6fSKAoiE6iAbpOcjRkENBiZ6EQDMH4CPIEpjyFUSY8BVLAQJVYszo6qUnEw11YQTpiWM+jztBNqiY76I3ng5UNHwozyU4AhMG5DOWjmcLJjPyaQpajeU/JhtSRjPZr5mgCEWb9rLJg9AEn0q3ClT9ZDNkJEIbgMDbNW+dvUk3cN5KwOobuBezNhyJprNvLyF/Z034EXNryWoO7s4atKHDMMu9RETeLGmCig4gKCRr4IDA1VmBAAAh+QQJBgBRACwAAAAAIAAgAIYcklSUsvwkrmRMgvQshqys4sRcrozc5vwkioQ0ftzs+vR0ypxEunxMopQcllS0zvxEitTc8uREfvQcjmxUjvT8+vx0zpykwvw0smw0gsTM2vx8sswshqQ8evTs8vz09vxUvoTk7vyE0qSEqvQckmScuvwsrmxUivQ0grwkipQ8gtRMunxsmvTE1vzk8uwkjnRkkvTU7tz0+vSMsvwcklyUtvxMhvQshrS04szk6vwkioyMwsQsmmS80vzc8uxEgvRckvT8/vx8zqSswvw0tnQ0gswsipw8fvSE0qyMrvwssmw8fuRMvoRsnvQkkmzU7uT0+vz+/v4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/oBRgoOEHw8bDU40ShggQjgyhJKTgzkjKhMADpoCnZ0mFj6UlFA1Rzeam5uerAJIFaODITAdBJq3q62eDKKjBzYdGbi4uqxKT5QhwEs0w5sAxawYvYNQtB0pAM650Z0MUIQlHR0JzsTdnkiyR+McquborBGCSeMdze/58Z4LUVA/44qYe8fKgSeDrRT0sMdh4K19ngrMsIcgnzOInRawsDfB4jto+wwyADYOn0OMnSTYc6gKHUJPAMex1FbwYLET9kx6BIlx47iOLFEymDiuokOe+xa0YLjTAbd9BSoMCHj05T4XUWqsbIrUaqt+UTyoxBY0mtUYgy6MK7cTaTewSoIq+DSa72k0IpEIeaBATuc5dPMmhcCJCl5NVmhHedjY0GI3DIFjBblwxJa+YgvyxhrkoQYEk24FLEi8eRKUFjsMOPW2oEBkSoEAACH5BAkGABoALAAAAAAgACAAhCSuZJTWtHTKnNTu5Ey6fPT69ITSrOTy7DSybKzixFTChHzOpNzy5FS+hPz+/IzSrLzmzCyybHTOnEy+hPT6/OT27DS2dLTizNzy7IzWrP7+/gAAAAAAAAAAAAAAAAAAAAWroCaOZHEtihVFVrNcBSnP47FEQK7v0cLQNMdjRywCDA7gqDIxOnUEjJKBeFoBkQGtYrleEVKSg+D1EiikYdm7WK7XP83iXRZoCji6t3LRlxNzflcCDYJXFl2GiouMTomNRIWQOwSBkzkCfZc5AXibADGWkHYaB5taIhmTpCIUZIwISSQYVYsHNAN5gqg0B690CLdKGhQGdAJowyMMAl4CvMolCQK/AAQCncMhACH5BAkGAEoALAAAAAAgACAAhhyWVJS2TKzixGSqTPzebNzy5MzGTCSuZPzuvHTOnOzSTPz25DyiXJTWtHyuTPz+9Ey6fLTCTPzmjNzKTPT69CyaVGSydITSrPzWTNTu5OTy7DSybEyiVPzqnPzaXCSWVKS6TLzmzHSuTNTKVPz23Pz65ESeVLTSlIy2TFS+hMTGTOTOTPz69IzSrPzaVJy6TLTizGyuTPzedNzy7MzGVCyybPzyxHzOpHyyTPz+/Ey+hLzCTPzmlNzOTPT6/DSeVGy2dPzWVOT27DS2dPzqpCSaVPz67ESiVLzWlIzWrP7+/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf+gEqCg4QPNjwyHkFBHjI8NiyEkpODJTxBGJmamxg8JZSUOUScpJwdkaCCJQSlrZoEn6ALHpsGKAMmFR8fFSYDKCqbLiSUJbQYKw4VAMzNzswVDhOZLrGDOawKIs/c3TEKGASogqM7y93ozh8RnZUYL+nxzwEYC4I8IPL6zS8SSg8j9gkEoIIFAg4D95lAgCShwBNAHO4bwECivl0W9R3YCOBAx48eQ4IcKTLkgSEbU6pcybKlyhQuY8pMCeHGzJstE8DAyTOlAAo1evIUosSm0JkJBGk4OjPDoCRMXd4g5ANCyo4cr2rNynFIDkkzNkRNWYPopAxBxzoFJcTq0SEeZlP5uCD0BoVUYBPcTLAW7yQKAhK43QghgQANeAMBACH5BAkGAEAALAAAAAAgACAAhhyWVJy6TMzObNTu5FyqXPzuvCSuZOzSTPzmjPz25JTWtHTOnPzebPz+9ESiVEy6fLzCTPzWTPT69OTy7ISyTITSrDSaVKy+TDSybPzqnKzixPzaXKS6TNzy5GSqTPz23Pz65FSmVFS+hPzaVPz69IzSrLzmzCSWVNTSdPzyxCyybPTSTPzmlHzOpPzedPz+/EyiVEy+hMTGTPzWVPT6/OT27Iy2TDSeVDS2dPzqpLTizKS+TNzy7GSuXPz67IzWrP7+/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf+gECCg4QNKSwuGzMzGy4sKSSEkpODICwzEZmamxEsIJSULzmcpJwZkaCCIAylrZoMn6AJG661ESMflCC0trUjsYMvrL22DA2Eo8S9GZWkKxA2HjAWFgAAJzcwHjYQK6SxLJorHCHW5ufo1jAcB5oIQA2YERQn6fb2JxTeET4pETLV7glMZwFChAIsLgxcaI8DAhT1GEo0J6DHxIsAQkTEKNGARwMAQIoMSXKkyZIlcXxcybKlS5YqRLycSfMjjhY1c7pcoEOnz48aJKj46bMGEJxEay4QNCFpzQGDfnwM6ZGqyKpTsxpoQYjGA6ctcbyQxAMD2JVGJw0YehYqqBoiMZziSJtKQgWiLSSkktRhQc4FbvdOkqBhwdePDxZomLA3EAAh+QQJBgA+ACwAAAAAIAAgAIUcllSUtkys4sT83mxkqkzc8uQkrmT87rzUykz89uQ8nlTs0lx0zpz8/vRMunz85oz0+vRMolT81kyE0qwsmlSU1rTU7uTk8uw0smzkzkz86pz82lysvky85syMtkz89tz8+uRUvoT8+vRUpkz82lSM0qwkllSUuky04sz83nRsqkzc8uwssmz88sTczkxEolR8zqT8/vxMvoT85pT0+vz81lQ0mlTk9uw0tnTk0lT86qT8+uxUplSM1qz+/v4AAAAG/kCfcEhstGapTa22Sc1aIqJ0OgTNapKsdiuZgajUmI5L5mqiYCFoUG5rB19wYuOuS0gfKohur5PiQzFsfXYDDURjhH0aVYqKcTOOhA8+DViSfTstmIRHXAgcHiojETYUJgAAJhQ2LyMqHhwIXA9sGScjqKm7vL2+IwEuEgMLKr7HyMcEGS/Jzs8KBtLTANLVBtfZ1tvT0zjd4OHi4NcGIePo6dMOMOru4gwo7/PTAhAs1PTpNz7t+uoMhFz4p87CkB7iyinMxw0GERoOCIbDEUPKCgwSu/GbYgFfRoNgbkT8h2NjGhoTuKmDASGNlAIM3DEA6XIKDQEMRkpzwEDABAWXQQAAIfkECQYAKgAsAAAAACAAIACFJK5klNa0/NZM1O7k/O68dM6c/Pbk/OaM/P70TLp8/N5s9Pr05PLshNKsNLJsrOLE/Npc/Oqc/NpU3PLk/Pbc/PrkVL6E/Pr0jNKsvObMLLJs/NZU/PLEfM6k/OaU/P78TL6E/N509Pr85PbsNLZ0tOLM/Oqk3PLs/PrsjNas/v7+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABsZAlXBIRHA8IchmAwl5OBeidDqseDaCrHYr8FSo1I+JS+ZGomBhRVFuaxVfsAHirgskFGqFbq9L4kMfbH12CghEY4R9EVWKinEejoQHKghYkn0oHJiER5x9B4Ofbgp8o6ejGgCrrK2ur7CsJLG0tawaFra6sAkdu7+sBSXAwA8LqsS6Iyq+ybUFQgzOtQNDKdOwHUQiCditDmhDJw7eqwxUA8jT1WAM3ckO52kqIg3EHQvzRBMFuhby+qQseFCAHKsEFozNCwIAIfkECQYAOAAsAAAAACAAIACFJK5klMZkzNJs1O7kfMJk/O68/NZMRLZk/OaM/Pbk7Nps/P70lNa0VLZkdM6c9Pr0NLJs5PLsTLp8hNKs/Npc/Oqc/N5srOLELK5ktM5s3NZs3PLk/Pbc/NpUTLp0/Prk/Pr0jNKsvObM1NJs/PLE/NZURLZs/OaU9Nps/P78VL6EfM6k9Pr8NLZ05PbsTL6E/Oqk/N50tOLMLLJsvM5s3PLs/PrsjNas/v7+AAAAAAAAAAAAAAAAAAAAAAAAAAAABvpAnHBIXJBOMUqpRImdSCCidDr8nEqGrHZrOH2o1BSMS+ZWomDhx1Juay1fcILirhs6HOqHbq934kMpbH12FgtEY4R9FVWKinEnjoQIOAtYkn02JJiER5x9CIOfbhZ8o6ejGharFKWurbCssq60rRoeNKu6u7y9vhY0ByoABwEjv8i8IwEHAC8rANHRDQQBGQIaCq26FAoaAhkBBA3S0Q4i5enq6+wXDxjs8fLRLjjQ8/jlDkIu+f4AG4bc+DdvBREWEgiya4FmiIsZCtVFoDIAQkRpA9LUSKgQwsQ0OFhMILiCBUgiGxzgc5Dx5JQHFxyYKGfCAYMHIIMAACH5BAkGADsALAAAAAAgACAAhSSuZJTGZMzSbNTu5GS6ZPzWTPzuvPzmjHTOnPz25Ey6fOzabPz+9JTWtDSyZITKhPT69OTy7HzCZNTWbPzaXPzqnPzebKzixITSrCyuZLTObNzy5PzaVPz23Pz65FS+hDS2dPz69HzGhLzmzIzSrJzKZMzWdGS+ZPzWVPzyxPzmlHzOpEy+hPTebPz+/DSybPT6/OT27ITCZNTWdPzqpPzedLTizCyybNzy7Pz67IzWrP7+/gAAAAAAAAAAAAAAAAb+wJ1wSGSkVDUKCkWpqVIhonQ69KhQhax2W1B5qFQXjUvmVqJgocdSbmstX3CC4q4XOB2qh26vc+JDLmx9dhYMRGOEfRVViopxKo6EBzsMWJJ9OSmYhEecfQeDn24WfKOnoxaqpawUraywrrGqsjOrt7i5urgmD7u/wKsiKxLBxrgSCDYABAvHwQsnABcQNwAOJbLPtxQlDgAAEDsr4AAZMgLbFgIy3+AIQjHl5RknARoTC9oLExoBJxnmgdswpIHAgwgTYiACg0XChwhBHCIS4QXEiwBuRKAyAATGhwPSRFDwUSCIGGmEwMBQEtwKcSmHbECAEUHImFMgXEBAspwHAgQXNqYJAgAh+QQJBgBAACwAAAAAIAAgAIYkrmScxmTU0mzU7uRcumzc2oT87rz81kxUtmT89uR8wmSU1rTs2mz8/vR8zqQ0smT85oz0+vS02qTk8uxMunz83my04sT82lyM0qw8smT86py0zmzk2mzc8uR0zpz89tz82lT8+uSMwmT02mw0tnT8+vRUvoS85swssmykymTU1mxkumTc3oz88sT81lRUumyEwmTs2nT8/vyE0qw0smz85pT0+vy83qTk9uxMvoT83nS04syM1qz86qTc8uz8+uz+/v4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/oBAgoOEDS01OhcuLhc6NS0lhJKTgyE1LgeZmpsHNSGUlDI9nKScGpGggiEVpa2aFZ+gCReutQcgH5QhtLa1ILGDMqy9thUNhKPEvRqVysqxNc7EEEANmNK9Py3YxIfcvRDD364VvOPn4xXqF+Xt7O/t8ezy6xUx6vj5+vv8+Aws/QIKxMfixsCD/CScEICwYQUVFiIQcHjwwosIQBwooChQgQdBOADAqMcRHwwAHQYtALCCQUl1DFYA4EHIRg4AD1KUTPEAAAWMhCaQAAAgQwCXAxkEyED0QcpJHWgQJYpAxAYVHC4wYKBigwgEU3EOSIXjZtizaIlSeJoqAoa0HXABOACaalAHD3GnemBbV1IECx7MEs3hwQKOuoEAACH5BAkGAB0ALAAAAAAgACAAhPzWTPzqrPzifPz23PzaZPzyxPzmlPz69PzaXPzuvPzijPz67PzedPzaVPzurPz65PzeZPz21PzqpPz+9PzWVPzihPz25PzyzPzqnPzmjPzutPzebPz+/P7+/gAAAAAAAAWvYCeOJHdJDNFQCGMUEynP4yEhQK7vjfHQQE1jRyxiDsCaoMgkbizJxaZJ1TUGtMO0ym38ZBWuGABBjhLjsWE0GabF2E7gPc6ICPTxYpAfO+Z9XBUZgVwQW4VUEIlVeIxNDI9NYZJEDRKVRAIRmTsOHDidAD+YnQIibZ0RIxqZdiMcS48NMSQLi4xfMg+4gatAC7J0XkmoEm51tcUiDxjITQK6yyQTBRkQyBACGso0IQAh+QQJBgBIACwAAAAAIAAgAIbcSkT0plz81kz83tzsglTkYkz88sT0vmT84oT89uT81mzkckz0vrzkVkTslpT8/vT0tlz87rT8zmz89vT83mTkbmTskozcUkT82lzsklT86pzkXlT0spT0rpT82lT85uTsilTkZkz89tT0xoT85pT8+uT82mTsdkz0xsTkWlTsnpz0umT86uT8znT8+vT83nTkdmzcTkT0rlz81lT84tzshlTkYlT8wmT85ozkdkz0wsTkVkz8/vz0tmT87rz80mT83mzkcmzcUkz89tz8+uz82mzsopz8+vz+/v4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/oBIgoOEEzodIy0KMxgvJAYPhJKTgx8OBTJAmkACnZ0eJCWUlEdGMQs/m5qerAIaR6OVFQAnRaoUQDOtnhQJsTQpAAWpqqu7nh5DlCwbAAA3xZsex8iihEezACCbuEDd1KwULoRGzjES3dHgrCSDLDHOBOm3QNPrncpIDs4AENya6e55woHkyA5nDWxF2yTQExEU/E50myetoYAI+5xliDaRk0UEQfgFSEfRY0MKzZz587awnkUBQvitoNjxpYAG/G6QVPcymMqSquw1DOlsZLGaFj1kBLAR4MKXCHREBFqxoYYJOAE0MPGPpbeXoizIpGry3gtBH+ABkNfSpUARWoNUmCPm9ZtAgoNcZNsGVKCHSIQ+BIsB7ahbcNYkDQgWQkFHY+Dgjvow6wTXYuA8JB41QUWMEwqKCWWFA3CsShYK+MNFYRcCyacnTWDAYYSEIgI8UEAQwTSlQAAh+QQJBgBGACwAAAAAIAAgAIbcSkT0rlz82lTsekz83tz88sT8xmTkakz0mlz89uT84oTkVkT0vrz0xsT8/vT81kzskoz0umT83mz87rTkdkz89vTkXkTsjlT80mT82mTkgmz86pzkWlTsnpzcUkz0smz85uT89tTkbmT0olz8+uT85pTkWkT8wmT86uTkcmz8+vT81mzcTkT0slz82lzsflT84tz8ymTkbkz0nlz85ozkVkz0wsT8/vz81lTslpT0vmT83nT87rzkXlT80mz83mTsgnTsopz89tz8+uzkdmz8+vz+/v4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/oBGgoOEFTY5QB8YOC47JQUOhJKTgyA5HgAHGBkSOA+fDwIlJJSURUEsAAAWGBKuAqCxG0WllSKqqhGurrG9Pwm1MBy4AAM/uxK9vQJClCg9xAAnu8fKy6SERbfEB8fIntagPyqEQdEACN7e4b0lgyip0Qbeu+y9zUY55wv09fagNIwUqXFuACdX6/6BGtLgHIAL/Xgp/DRB37kZEZNNfKAghcMA9BJO/AHtXISMGz9hMqnO38YFDk8cRJbywbBzLY71q+kRZ79qGwVYjDYiIziFCmw4hIjQpcINFWBGM4bs1UZSEPaFlPBj4w5BIOIRixFxY4hBHS5GhPUv4CAVTdtwdauqUEAkQiBu4jrRUiE2SQRMEBtQlW24s6VAxF1w0um1WoIqdJBqYoXIXjTuQhYEI2smyxIMf1KAeLOkBAwgvPiwItQPBRM0UwoEACH5BAkGAEIALAAAAAAgACAAhtxKRPSmXPzWTPze3Ox6TPzyxORuTPzihPS6ZPz25OyWVORWRPzWbPS+vPz+9OySjPzutPzGZPz29NxSRORuZPzeZPzaXPzqnPzCZOReVOyenOR2bPSuXPzaVPzm5OyCVPz21PzmlPy+ZPz65PSiXORaVPTGxPzq5Pz69ORSRORybPzedNxORPzWVPzi3Ox+VPzmjPS+ZOyaXORWTPzaZPTCxPz+/OyWlPzuvPzKZNxSTORubPzebOyinPSyXPz23Pz67Pz6/P7+/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf+gEKCg4QSNTcqGQgtFishBQ6EkpODHjc6AJkKPC0CngIdISOUlEE9LJmZKQwVn64CF0GklRSpqQQVPK+uFQmzLiW2qQE8urufHT+UJxnCKZk5uceuHaOEQTvCqSm5xtOeFSiEPdrPAAY0xd+uIYMnqNqZuOrrn8pCN862Ct31nzBCgphTJYxEP3+egJiIZ4vDQYQQ8hHU5uOhvwMbGKYSYbFehWYaAUToWA8TgIHCRtJDKABlPJXeEILUiIHkOhUhAXBc6a+DRJepKvKsd6BGTqEx612QANSWwaHrRj0IqSBd0m8rBHloKs/mMRCDNGg04PUVwEEoasXjBnVXh0hChDzMAJoiQttX1iQNmBHvaT2wpDyotTXvW7VZgiRoQLnqqicYcBELcvFgIL9Org4AliwpQYMHFDKIAFUBBoS8lAIBACH5BAkGAC4ALAAAAAAgACAAhdxKRPzWTPzihPzi3OySjPzyxPS+vPz25ORuZPzaZPz+9ORWTPzutPz29PzaXPzqnOyenPze3OR2bPzedNxSTPzaVPzmlPzq5Pz21PTGxPz65ORybPzeZOReVPz69NxORPzWVPzmjPzm5OyWlPTCxORubPz+/ORaVPzuvOyinPz23Pz67PzebPz6/P7+/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbfQJdwSGyQRpvTB+SYWAoKonQ6FI0ogGw2wOVWLBoqtZX6aM/ddODRElcR57g6zTm4B6e4fN6tqKgXHXp7fF5hRC0lg4SFARweRCmLjI0WQxdmk1qNan8uI5ponF0hLi0LoZujXSsZqaqrAQygrwCxXAIbtba3HIK1t1xYwMGoxLd5x7G6yqMVtK/BAiS7wQ8NxqnBYQTNjRNCIpmhtxhDENGrpUMecOTOUUQiyZOrh1IRC+N6o+ZiIu4GNapwT0wDCPtgqQkRz00VAgnnCPDncMoBAwQQ6OPCQQCDglOCAAAh+QQJBgBFACwAAAAAIAAgAIbcSkT0pkz81kzsekz83tz88sTkYkz0lkz8vkz84oT89uTkVkzsbkz0vrz8/vT82mTskozkbmTshkz87rT89vT80kzkXkz0rkz86pz83nTsnpzkdmzcUkz82lzsgkz85uT89tT0okz8xkz85pT8+uTkWkzsdkz0xsT83mTkcmzsjkz86uT8+vTcTkT0qkz82lTsfkz84tz0llT8wkz85ozsckz0wsT8/vzslpTkbmzsikz87rz80lTkXlT0skzsopz89tz8+uzkWlT83mz8+vz+/v4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/oBFgoOEFDY4KUIcMh0ZIwUOhJKTgx84HACZAC0lLgKfLyMklJREPy2ampwMn60CGESklRGpqZwlCK6fKAqyMUK1qQsLJQe6oECUKz3BtSUlA8ego4REOc22zxbSuyyEP9jCxCUi3AIjgyuo4ZrPJT7mAslFOOyaw88B8TRFRAv27Z4ZixfkBMBM+EroiCdgQr2DANxJYJggBcSEMBh2YAbRXTSGmA4mNMFQwL+Oz0gyBCZy3Md4FlFCY/jiIcCEHijagBjx2cJ4GCictJdwoLlREGSGiJdB0Id17BJeiAdikIaD7nJx4zeIBQOi4ypwe+GN0AeW4Z7VOEqJQIlwOvgOiD1WldSHr9hKLJiq6wU1WRQ0DL23wMDcVjQiySIUA8LgiEYFJKi7eJKCBhAYDGNQAUWCCX8pBQIAIfkECQYAQgAsAAAAACAAIACG3EpE9KpM/NZM7IJM/N7c5GJM/PLE9JJM/Pbk9L68/OKE7HJM5FZM7JKM/P70/MpM/Npk/O60/Pb05G5k5F5M7I5M9J5M/Oqc7J6c9MJ05HZs3FJM9LZM/Npc7IZU/Obk5GpM/PbU/Prk9MbE/OaU5FpM/N5k/Ork/Pr05HJs3E5E9K5M/NpU7H5c/OLc5GZM9JZM9MLE/OaM7HZM7JaU/P78/M5M/O685G5s5F5U9KJM7KKc/MZs/Pbc/Prs5FpU/N5s/Pr8/v7+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/6AQoKDhBIxNCk/KgUtGSQGDoSSk4MfNBsAmZkUJSU6AgIkPpSUQTsqmqmcnSugAhdBpJUTqbWrJQUPrkAIsi4/tbadnRWuAiw9lCc5wcLDJbquLCKSQTjNzsMWxgImKIQ72NmdC9yhgyeo4pq3w9HGyUI066rPrOYyQkEM9Oz2JQfMCfAxop8/ewMERphnEEA7cgIVpGjo8F8BgR2YNXzYSaAATBv/lfDIL+Q/j8BMPqPgcaLKYS8EsmBokGM5cwpiUOSY0NwFCSX7cYQhkFqDl/e4ARH0QR09ju9chRiEoaa9GfgIoaD11N4nYyy+EfpQouswCja4UZtEoKy4djYBjU0l9YFrs1sv0oKaJkuQBAxO63Xi4EpGpL6VGgSuWCIAKAVzEUtCkKDBAn4LBvBQEGEtqUAAIfkECQYASwAsAAAAACAAIACG3EpE9KZM/NZM7Hpk/N7c5GJM/PLE/L5M9JJM/NaU5G5M/Pbk5FZM9L687JKM5G5k/P709KZ0/Npk/Oq8/Pb09LJM7IZM/MpM/OKE5F5M9KJM7HZM7J6c5HZs/Oqc3FJM/Npc7IJM/Obk5GpM/PbU9JpM7HJM/Prk5FpM9MbE5HJs/N5k/Ork/Pr0/LZM/NJM/OaU3E5E9K5M/NpU/OLc5GZM/MZM9JZM9MLE7JaU5G5s/P789LKM/O609LZM7IpM/MpU/OaM5F5U7KKc7IJc/Pbc7HJU/Prs5FpU/N5s/Pr8/v7+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/6AS4KDhBQ4OSpIMUZEEQkGEISSk4MiOR8AmZkonCgWQDAnlJRKQzGaqJ2cBS4CHkqjlQ+otKqcGTICSQuxNEi0tbYoGQcCM0WULELAwcImF8aihEo6zM3CNwICKy2EQ9bXthnQAjCDLKfgmsKqJdoCyEs56qnsnCPvQUtKDPTr9pyKaTuSwt8/gBre9ZhnEABAThbeYVDR0OHDDe9ALGv4EEWNdwIwcXxYAGS/kQBLvvuF0t7HdxRbsjPxbgZDgx1DSMRRsaM7bR4onPTXsdXAJQ5k2irwQlsSQSLS0XuIoKkAEoM44AQoUN+gFkaI2tNprBshEUOt2StgQ5s0STgEUKizF0Ab1lEiwqoVhkAAiHixKHBIe7BTtiCRYhGi4YCwqhouMABWLGlBAwdG+g0LwWPCEcWBAAAh+QQJBgAgACwAAAAAIAAgAIXcSkTspqTsjoT02tzkamT88vTsnpTkVkz85uT0vrzkcmzslpT84tz0xsTcUkzskozkbmT8+vzsopzkXlT0wrzcTkTsjoz83tz89vTsnpzkWlT86uTkdmz84uTkbmz0wsT+/v4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGwECQcEjEfBYcjeOgUTw+GKJ0OkQsHICsdnt4IKjUiKSyLZcrmQh4uPGY32XCF8zQwO9azYC6seP/GnNDEW5/hgRqQxKGjAAGbGSNfxUMQguSjAIgGFiYkwUUnowJD6KGAgqmfxB+qnAHka6vsnettFypt2UQl7pbAg2+WwkYB8IABwUgvb6aIBuxtBWCAb6PgxC3iFJ9sgeVU3Wq32sb2Z4Q4GtixowVBlFrRAgP7a8C6vJSGBQCEAfGDkAQQExeEAAh+QQJBgBRACwAAAAAIAAgAIY8evSErvScZpS8gpy80vzcSkTEYmxscsT02txMhvT0vrzMXmTk7vxUdtycvvykptzslpTkamTcWlSUtvzk6vz09vxUfuTcXlREfvTsjoTkcmz0+vyMrvS8YnTc5vzcUkxckvRkcszsnpTkVkxMduSsZoTkTkTManSMaqT84tz0wrxcctScuvzkbmT85uT88vTskoyMsvxkkvTsopzkWkykZoy8hpzE1vzcTkTMZmx0brzUXly8zvykruSUuvxUfuzkXlREgvTsjozkdmz8+vyMrvzc6vzsnpxMduz84uT0wsRcdtTkbmz86uT89vRklvTkWlT+/v4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/oBRgoOETkoQQ1AfIxIaMEpOhJKTgy4QHwWZmiaaIzAulJREMzgFnKeappo4R0Shg01Mqqm0qZwRoKEpEpyZvbXANAiUTRLAtL+2BTRJkkSyycq+qtERroMzs8jTx9MQsKXb26iomymCENqb1N21GVFOH8nR07327KYvKsDk7ccKMLTR87cuUwYN/NQRnBYBisCF7UyYkIdDokRTFjNq3GjR1AUaIEfQEDmipMmTKFOWpHECpMuXMGPKdJnDxsybOF0O6JGzp8wHNwT4HEqjBI8KFhYQzXmBxIYoMRrsWHpzSQBBDDCsUEr1pYQlACgMcgCARImuIDuQAOCDEJEnYQAAhDCwdMGBuCCeEmKQIC6AFTWm3pRQ427cBGInGenrF0ADHSgE1CghAIUOsI0TeHjFAG7jzwAwgJaR+BURFqJBq8YwQe+rQQxipFYdmoOR16E2EODwJIHoBE848HBNKRAAIfkECQYATAAsAAAAACAAIACGPHr0hK70nGaU7I6ExNb83EpEbHLE3Ob85GpkTIb09Pb8zF5kvM78VHbclLr8/OLc3FpU7J6URH70bJLslLb8pHac9L685HJs9Pr85F5UTHbkjK70rGaE7JaU3FJMhG6s5O78XJL0/Ork5FZM9NrcpG6U7JKM5E5E5Or85G5k/PL01F5cXHLUnLr8/Obk7KKc9MK8jLL8ZJL05FpMRHrspGaM7I6M3E5EfG603Or8vNL8/OLk7J6cRIL0dJbs5HZs/Pr8THbsjK78lGqc5G5s/Pb01F5kXHbUnL789MLEZJb05FpU/v7+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/6ATIKDhEVJHT9LHiMQFyZJRYSSk4MuHR4FmZonmiMmLpSUQC83BZynmqaaNzxAoYMiRKqptKmcCKChDxCcmb21wDMklCIQwLS/tgUzO5JAssnKvqrRCK6DL7PI08fTEbCl29uoqJsPgh3am9TdtQNMRR7J0dO99uymKjDA5O3HFia00fO3LtOAC/zUEZyGYInAhe1OnJB3Q6JEUxYzatxo0dSKGSBHzBA5oqTJkyhTloRQAaTLlzBjynRZwseCmThzzlgxIYaGmzqDglzRIAABADQECNXJgQYABgp6AADAosbSmBwMTJWggEmMqVNp4ODwMSiHDxrAAgggCIQEtV1gGxj4IKCG3RoChuBoABcsikFI+goeDNcBISBKCCuGKwODJBAJFi9O8HdSjsiSBSc48ApE4sxqZVR+BaTFW9AOHL8iBGKDVMI9AoBYHUqBjg1KErxNoGSDjq6vAgEAIfkECQYARwAsAAAAACAAIACGPHr0hK70nGaUxNb87I6E3EpE3Ob8bHLE5Gpk9Pb8XJL0vM78zF5klLr8/OLcRIL07J6UvGJ0bJr0lLb8rGaE9L68hGqs5HJs9Pr85FZMTHbkjK70pGaM7JaU3FJM5O78/Ork9Nrc5F5UnGqU7JKM5E5E5Or8fG605G5k/PL0ZJL0nLr8/ObkTIL07KKc9MK85FpMjLL8RH707I6M3E5E3Or8dHK8vNL8/OLk7J6clGqc5HZs/Pr8VHbcjK78nGqc5G5s/Pb0ZJb0nL78TIb09MLE5FpU/v7+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/6AR4KDhEFFHTtGHhlGFyRFQYSSk4MsHR4FmZqbGSQslJQ8LjQFJaWnp6aZNDk8oIMgQKibtJqmCJ+gDkabqrW/MCGUILyZvr+1pjA4kjyyxsmps5sIroMu0NHRxyUQsDTHtr3T2aUOgh3I4rSm4ZkER0Ee4e3iqtyzJSkv6uT9qBVI5Bv4rxaBC8jcFVSFgJevhwV/lSgxD9zEi6UuatzIsd0IGCAzwMggkqTJkyhTiuRA5EAEkDBjypw5k4GNBxIAANBwggMDmkBhMohgQYNOFTF0KtXZ48AJHToEcJg6dYQFCzZ6GF0KIMAArmDDil26IMGDsWjHPkhwJGnat1BLAwj6IAOu3Q+Dhth924AQDxV7xyqwNugDkcBgieCdVOMwYp1EDLz6IOSxisWveKyoC1dGAwyvJH3YcFbtBhOhQSW4sUEIkbpEhGy4wfZVIAAh+QQJBgA5ACwAAAAAIAAgAIU8evSErvTUTkzE1vzsjoTc5vzkamT09vy8zvxckvSUuvzkVkz84tzsnpREgvSUtvzUUlT0vrzkcmz0+vyMrvTslpTk7vxsmvT86uT02tzcSkTskozk6vzkbmT88vRkkvScuvzkXlT85uTsopxMgvT0wryMsvxEfvTsjozc6vy80vzkWlT84uTsnpzcUkzkdmz8+vyMrvzcTkTkbmz89vRklvScvvxMhvT0wsT+/v4AAAAAAAAAAAAAAAAAAAAAAAAG7cCccEik4SqvlWuxkmxwNKJ0OhRVXJqsdrvYiKhU2Ei2LZdlLRh4iJmZ32XDF8xYwe/aVYaKseP/K3NDMG5/hgZqQyOGjBoNbGSNfzIMQhWSjAQ5NFiYkx4lnowRG6KGBBKmfx1+qnALEGSyGrO1tLe2tScAvLu+AL/BwMPCuze8yMnKy8zIJxfN0dLIHybT18wBA9jcyAgHDt3YJwc51uLTAUIWu+jNJxxDNu7ND0QwNfTKH+VEFsf6AJCINyUFQHckCqyxkA/dB4JrYIBod+3Eg35rhligEC7aCQoQM0o5oIJCDRK7SNSg8C1jEAAh+QQJBgBLACwAAAAAIAAgAIYsYryErvScUmzE1vw8evTsjoTc5vxkWpTETlT09vzkamRMXqS8zvxckvSUuvz84tzcSkTsnpRcWpw8YrSUtvz0vrxEgvSEVnz0+vzkcmzkWlSMrvTslpTk7vxUXpxsmvT86uT02tw0YrTskozk6vxsWozUXlz88vTkbmRMYqxkkvScuvz85uTcUkzsopz0wrxMgvSMsvy8TlxEfvTsjozc6vzMVlxMXqy80vz84uTcTkTsnpxcXpxEXqyMVnz8+vzkdmzkXlSMrvw0YrxsWpT89vTkbmxklvScvvz0wsRMhvT+/v4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/oBLgoOERUkcQBotLUEZI0lFhJKTgywcLRCZmpstIyyUlD8uOpulpTo7P6CDIEamr6UKn6APGrC3mhohlCC2uL8as4M/rr/GCqqDLsbMEBGspM2/Og+CHNLMBUtFmNjTJy/ezBUjpQgyFxcHHgs9E+8TPQseByU+MjKlBRkQCAI8EwAIHEiwoAiCIg4IQAABhQkiBSNKnAhARAkbNyhq3LhgBoGPIEOKHEkSpJKSKFOCtPBBpUuSR2K8nAkywACaNBkksIDTpYUES2T2TBlAUAePQ0nOIDEISVKSDgj9OPI0ZINkgzqcrKqkA6UaW4cqMbCqA9WeR7yuWvJjBVKfHRQwrCXUIQZPlBYCMJ07CQOOGEeUeFQSEwfQVYEAACH5BAkGAEwALAAAAAAgACAAhixivISu9JRSdMTW/OyOhDx69NRKRNzm/GRalPT2/MR2hLzO/FyS9JS6/Pzi3ERerOyelORaVHxWhLxyfJS2/KxSZPS+vESC9NxSTPT6/ORqZDxerIyu9JxSbOyWlNxKROTu/FxmpGya9Pzq5PTa3ORybDRitOySjOTq/Pzy9GSS9Jy6/Pzm5FRenOyinIRWfPTCvEyC9Iyy/JRWdOyOjER+9NRKTNzq/GxalLzS/Pzi5OyenOReVPz6/ORubIyu/JxSdNxORGxqpOR2bDRivPz29GSW9Jy+/FRepIRWhPTCxEyG9P7+/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf+gEyCg4RFSh5DERgYPCUnSkWEkpODLB4YH5mamxgnLJSUPS5Bm6WlQTs9oIMjPqavpRqfoA4RsLeaESSUI7a4vxGzgz2uv8YaqoMuxswfEKykpRUzEi1IG9gbSC0SMxWmQQ6CHpsdLSYA6err7C0VBpoETEWYHy/o7Pn6ACYvmUEpYHyo8GCfQX0Pvlk40YHIwYf5OhBQgA+ixXQThFzcCCBERY4PTdQoQLKkyZMoU5ZcorKly5IxRLycmVKFDJo4SwYYkDPnggQXes68kIDJTaEuAwgCMRJpyhooBh1xmrIBoR5GqJpkkGwQCJZal4CgdGNJU6FLbqwCoQKpkbEmq5j0WHH25YUGGeISAiGjLsoLHKLqnZQhxw8jZi8sMSIjR9FVgQAAIfkECQYAUAAsAAAAACAAIACGLGK8hK70lFJ0xNb8PHr0tJasxE5U3Ob8ZFqU9Pb8bHq05GpkvM78TF6klLr87I6E/OLcrFJk3EpEfFaEXJL07J6UlLb89L68RIL09Pr85FpUPGK0jK705O78dFaM5HJsRGa0/OrktFZkbJr09NrcNGK0pFJs5Or8/PL0nLr87JaU/Obk3FJMjFZ8ZJL07KKc9MK8TIL0jLL8lFZ0RH70vJq0zE5M3Or8bFqMdIK05G5svNL8VF6k7JKM/OLktE5c3E5EhFZ87J6c/Pr85F5UjK78dFqM5HZsTGq0vFpkNGK8/Pb0nL78ZJb09MLETIb0/v7+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/6AUIKDhEtOKkcaLCxEHz1OS4SSk4MrKiwSmZqbLD0rlJRDL0CbpaVAQkOggyE6pq+lC5+gEBqbPy04PBu8Gzw4LT+bGiSUIbYSBhMbAM3Oz80bEwaZGrODQ642HtDd3kY2Eguqgy8SESXe6tAlJhIVrEAC6/TQLRI+girz9f3NAg+gLEmSzp8/ESicNDBosMGFGgwZFsgR0aACJBX9gVCS0R8NAiBDihxJsmTIJyZTqgwZY8TKlyVdyIBJM2SAHTVrMsiAIedLGgmgzPSpMoCgDh+JlqRxYhATpSUdEBrSBKpIFxkkdUBp9UkHSjeeJPX55MCqDi6Iuvi6CsqQFCFjV9KwkLXtoA4y4pKkwaGp3UkZdnBoIpbAkyYcdgRdFQgAIfkECQYAHgAsAAAAACAAIACEPHr0nL78hKr03Ob8XJL0lLb89Pb8RIL0tM78jLL8jK705O78bJr0xNb8RH705Or8ZJL0nLr8/Pr8TIL0vM78PH70hK703Or8lLr89Pr8jK78ZJb0TIb0vNL8/v7+AAAABbagJ45k1igM5zgco3UGKc/jkjhAru+HttA0SQS3K+4chQywtjE6i4TH8sJ5WnWcAW2huno5UpKk6S0TJKRIeQ0o1CrsciWciK8FnszEXnYYOnxrCHWBXgJkhVYQVYlWB0SNT5CRRoyURRMMl0YbhJs6Ag2fOzAHowB+Hp6bFiILk5EOYR4BnxhiiI1nMlyRHD8zVIlZSwu5bBDAS0KwVg4YSkskNs08FrPSMhkdGhsqFRwbLzFLIQA7\');
                        margin:10px  0px ; 
                        height:500px; 
                        width:700px; 
                        border :1px solid grey; 
                        padding:1px; 
                        z-index:1000000;
                     
                 }
                </style>

                <div style="margin:10px  0px ;"><b>Find the coordinates with Google Map:</b> </div>
                <div id="map" >
                    
                  
                </div>

                <script src="https://maps.googleapis.com/maps/api/js?v=3&sensor=true"></script>
                <script>
                    function initialize() {

                        var latitude = document.getElementById(\'latitude\').value;
                        var longitude = document.getElementById(\'longitude\').value;
                        if(latitude=="")latitude="48.856951";
                        if(longitude=="") longitude="2.346868";
                       
                        
                        var zoom = 10;

                        var LatLng = new google.maps.LatLng(latitude, longitude);

                        var mapOptions = {
                            zoom: zoom,
                            center: LatLng,
                            panControl: false,
                            scaleControl: true,
                            mapTypeId: google.maps.MapTypeId.ROADMAP
                        }

                        var map = new google.maps.Map(document.getElementById(\'map\'), mapOptions);

                        var marker = new google.maps.Marker({
                            position: LatLng,
                            map: map,
                            title: \'Drag Me!\',
                            draggable: true
                        });

                        google.maps.event.addListener(marker, \'dragend\', function(marker) {
                            var latLng = marker.latLng;

                           document.getElementById(\'longitude\').value=latLng.lng().toFixed(6);
                           document.getElementById(\'latitude\').value=latLng.lat().toFixed(6);
                        });

                    }
                    document.observe("dom:loaded", setTimeout(function(){initialize()},5000));
                </script>'
        // 'after_element_html' => "<a href='http://www.wyomind.com/services/point-of-sales.html' target='_blank'>" . Mage::helper('pointofsale')->__('Find the latitude and longitude of a point on a map.') . "</a>"
        ));


        if (Mage::getSingleton('adminhtml/session')->getPointofsalePlaceData()) {
            $form->setValues(Mage::getSingleton('adminhtml/session')->getPointofsalePlaceData());
            Mage::getSingleton('adminhtml/session')->getPointofsalePlaceData(null);
        } elseif (Mage::registry('pointofsale_data') && $this->getRequest()->getParam('place_id')) {
            $form->setValues($model);
            $collection = Mage::getModel('pointofsale/pointofsale')->getPlace($this->getRequest()->getParam('place_id'));
        }

        return parent::_prepareForm();
    }

}
