<?php
/**
 * Customer Navigation template
 *
 * Description:
 * - Override rwd/default
 * - Add icon
 *
 *
 * @category    design
 * @package     rwd_default
 * @copyright Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license http://www.magento.com/license/enterprise-edition
 */
?>
<div class="block block-account">
    <div class="block-title">
        <strong><span><?php echo $this->__('My Account'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul>
            <?php $_links = $this->getLinks(); ?>
            <?php $_index = 1; ?>
            <?php $_count = count($_links); ?>
            <?php foreach ($_links as $_link): ?>
                <?php 
                    $_url = $_link->getUrl(); 
                    $_class = '';
                    if (strpos($_url, 'customer/account')) {
                        $_class = 'flaticon-user146';
                    }
                    if (strpos($_url, 'redeempoint/customer')) {
                        $_class = 'flaticon-credit82';
                    }
                    if (strpos($_url, 'customer/address')) {
                        $_class = 'flaticon-situation';
                    }
                    if (strpos($_url, 'sales/order/history')) {
                        $_class = 'flaticon-cart3';
                    }
                    if (strpos($_url, 'review/customer')) {
                        $_class = 'flaticon-star-shape1';
                    }
                    if (strpos($_url, 'newsletter/manage') || strpos($_url, 'monkey/customer_account/index')) {
                        $_class = 'flaticon-mail59';
                        
                        /* currently hide newsletter tab (task: http://teamwork.icubeonline.com/tasks/6366434) */
                        continue;
                    }
                    if (strpos($_url, 'wishlist')) {
                        $_class = 'flaticon-heart13';
                    }
                ?>
                <?php $_last = ($_index++ >= $_count); ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="current<?php echo ($_last ? ' last' : '') ?>"><a href="<?php echo $_link->getUrl() ?>" class="<?php echo $_class ?>"><strong><?php echo $_link->getLabel() ?></strong></a></li>
                <?php else: ?>
                    <li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>" class="<?php echo $_class ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
