<?php
/**
 * Checkout Login Step Template
 *
 * Description:
 * - override RWD/default
 * - override Inchoo Social Connect ext
 * - Remove all content from inchoo (except the inchoo_socialconnect_checkout block) with content from customcheckout by ICUBE.
 * 
* @category Inchoo
* @package SocialConnect
* @author Marko Martinović <marko.martinovic@inchoo.net>
* @copyright Copyright (c) Inchoo (http://inchoo.net/)
* @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
*/
?>
<?php /* get config */ ?>
<?php $isCustomEnabled = Mage::getStoreConfig('customcheckout/config/enabled',Mage::app()->getStore()); ?>
<?php $isSkipBill = Mage::getStoreConfig('customcheckout/config/skipbilling',Mage::app()->getStore()); ?>
<?php echo $this->getChildHtml('login_before') ?>
<div class="opc-content-wrapper">
    <div class="col2-set<?php if (!$this->helper('customer')->isRegistrationAllowed() && !$this->getQuote()->isAllowedGuestCheckout()) echo ' login-only' ?>">
        <div class="col-1">
            <h3><?php echo $this->__('Have been registered?') ?></h3>
            <?php echo $this->getMessagesBlock()->toHtml() ?>
            <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
            <div class="fieldset">
                <?php echo $this->getBlockHtml('formkey'); ?>
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                <ul class="form-list">
                    <li>
                        <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <div class="input-box-inner email">
                                <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" placeholder="<?php echo $this->__('Email') ?>" />
                            </div>
                        </div>
                    </li>
                    <li>
                        <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <div class="input-box-inner password">
                                <input type="password" class="input-text validate-password required-entry" id="login-password" name="login[password]" placeholder="<?php echo $this->__('Password') ?>" />
                            </div>
                        </div>
                    </li>
                </ul>
                <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                <input name="context" type="hidden" value="checkout" />
            </div>
            <div class="buttons-set">
                <button type="submit" class="button" onclick="onepageLogin(this)"><span><span><?php echo $this->__('Login') ?></span></span></button>
            </div>

            <ul class="form-list">
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                <li>
                    <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="f-left"><?php echo $this->__('Forgot your password?') ?></a>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
            </form>
        </div>
        <div class="col-2">
            <h3>
                <?php echo $this->__("Don't have account?") ?>
            </h3>
            <p class="description"><?php echo $this->__('Checkout Quickly & Securely in 2 easy steps. All you need is only email address, billing delivery detail and payment information') ?></strong><br />
            <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                <ul class="form-list">
                    <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                    <li class="control">
                        <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()!=Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
                    </li>
                    <?php endif; ?>
                    <?php if( $this->helper('customer')->isRegistrationAllowed() ): ?>
                    <li class="control">
                        <input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" />
                        <label for="login:register"><?php echo $this->__('Register and Checkout') ?></label>
                    </li>
                    <?php endif; ?>
                </ul>
            <?php else: ?>
                <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
            <?php endif; ?>
            <div class="buttons-set">
                <p class="required">&nbsp;</p>
                <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
                    <button id="onepage-guest-register-button" type="button" class="button" onclick="checkout.setMethod(); <?php if( $isCustomEnabled && $isSkipBill ) : echo "billing.skipBilling();" ?><?php endif; ?>"><span><span><?php echo $this->__('Continue') ?></span></span></button>
                    <button id="custom-guest-checkout-button" type="button" class="button"><span><span><?php echo $this->__('Guest Checkout') ?></span></span></button>
                    <button id="custom-register-checkout-button" type="button" class="button"><span><span><?php echo $this->__('Register & Checkout') ?></span></span></button>
                <?php elseif ($this->helper('checkout')->isCustomerMustBeLogged()): ?>
                    <button id="onepage-guest-register-button" type="button" class="button" onclick="window.location='<?php echo $this->helper('checkout/url')->getRegistrationUrl();?>'"><span><span><?php echo $this->__('Register') ?></span></span></button>
                <?php else: ?>
                    <form action="<?php echo $this->getUrl('persistent/index/saveMethod'); ?>">
                        <button id="onepage-guest-register-button" type="submit" class="button"><span><span><?php echo $this->__('Register') ?></span></span></button>
                    </form>
                <?php endif; ?>
            </div>
            
            <?php echo $this->getChildHtml('inchoo_socialconnect_checkout')?>

        </div>
    </div>

    <script type="text/javascript">
    //<![CDATA[
        var loginForm = new VarienForm('login-form', true);
        $('login-email').observe('keypress', bindLoginPost);
        $('login-password').observe('keypress', bindLoginPost);
        function bindLoginPost(evt){
            if (evt.keyCode == Event.KEY_RETURN) {
                loginForm.submit();
            }
        }
        function onepageLogin(button)
        {
            if(loginForm.validator && loginForm.validator.validate()){
                button.disabled = true;
                loginForm.submit();
            }
        }
    //]]>
    </script>
</div>

<div class="buttons-set">
    <a href="<?php echo Mage::helper('checkout/cart')->getCartUrl() ?>" class="back-link"><?php echo $this->__('View Cart') ?></a>
</div>