<?php
/**
 * Review list template
 *
 * Description:
 * - Override rwd/default
 * - move review form position to top
 * - remove link to detail review
 *
 *
 * @category    design
 * @package     rwd_default
 * @copyright Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license http://www.magento.com/license/enterprise-edition
 */
?>

<?php $_items = $this->getReviewsCollection()->getItems();?>
<div class="box-collateral box-reviews" id="customer-reviews">
    <?php echo $this->getChildHtml('review_form') ?>
    <?php if (count($_items)):?>
        <div class="review-list">
            <div class="review-heading">
                <h2>
                    <?php echo $this->__('Customer Reviews') ?>
                    <span><?php echo count($_items); ?> item(s)</span>
                </h2>
                <?php echo $this->getChildHtml('toolbar') ?>
            </div>
            <dl>
            <?php foreach ($_items as $_review):?>
                <dt>
                    <?php echo $this->escapeHtml($_review->getTitle()) ?>
                </dt>
                <dd>
                    <?php $_votes = $_review->getRatingVotes(); ?>

                    <?php echo nl2br($this->escapeHtml($_review->getDetail())) ?>


                    <?php if (count($_votes)): ?>
                    <table class="ratings-table">
                        <colgroup>
                            <col class="review-label" />
                            <col class="review-value" />
                        </colgroup>
                        <tbody>
                            <?php foreach ($_votes as $_vote): ?>
                            <tr>
                                <th><?php echo $this->escapeHtml($_vote->getRatingCode()) ?></th>
                                <td>
                                    <div class="rating-box">
                                        <div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
                                    </div>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                    <?php endif; ?>


                    <span class="review-meta">
                        <?php echo $this->__('Review by %s', $this->escapeHtml($_review->getNickname())) ?>
                        /
                       <?php echo $this->__('(Posted on %s)', $this->formatDate($_review->getCreatedAt()), 'long') ?>
                    </span>
                </dd>
            <?php endforeach; ?>
            </dl>
        </div>

    <?php // echo $this->getChildHtml('toolbar') ?>
    <?php elseif($this->getParentBlock()): ?>
        <?php echo $this->getParentBlock()->getReviewsSummaryHtml($this->getProduct(), 'short', true)?>
    <?php endif;?>
</div>
