<?php
/**
 * Veritrans VT Web Model Standard
 *
 * @category   Mage
 * @package    vtbcaklikpay/form.phtml
 * @author     Kisman Hong, plihplih.com
 * this template is rendered when Veritrans payment method is chosen. This is description about Veritrans Payment Method
 */
?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <?php if(Mage::helper('vtbcaklikpay/data')->_getInfoTypeIsImage()) { ?>
    <li>
        <img src="<?php echo $this->getSkinUrl('images/logo_veritrans.gif') ?>"/>
    </li>
    <?php } ?>
    <li>
        <?php echo Mage::helper('vtbcaklikpay/data')->_getFormMessage(); ?>
    </li>
</ul>
