<?php
/**
 * Product viewed template
 *
 * Description:
 * - Override rwd/default
 * - change layout to follow product list template
 *
 * @category    design
 * @package     rwd_default
 * @copyright Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license http://www.magento.com/license/enterprise-edition
 */
/* @var $this Mage_Reports_Block_Product_Viewed */
?>
<?php  
$_helper = $this->helper('catalog/output');
$storeId = Mage::app()->getStore()->getId();
$isAjaxAddtoCart = Mage::getStoreConfig('addtocartajax/option/addtocartajax_enabled', $storeId);
?>
<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<div class="block block-list block-viewed box-collateral">
    <div class="block-title">
        <h2><?php echo $this->__('Produk yang Terakhir Dilihat') ?></h2>
    </div>
    <div class="block-content">
        <ul id="recently-viewed-items" class="products-grid products-grid--max-5-col">
        <?php foreach ($_products as $_product): ?>
            <li class="item" data-id="<?php echo $_product->getId(); ?>" data-category="<?php echo $_product->getCategoryId(); ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <?php $_imgSize = 210; ?>
                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
            </a>
            <div class="product-info">
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php
                // Provides extra blocks on which to hang some features for products in the list
                // Features providing UI elements targeting this block will display directly below the product name
                if ($this->getChild('name.after')) {
                    $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                    foreach ($_nameAfterChildren as $_nameAfterChildName) {
                        $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                        $_nameAfterChild->setProduct($_product);
                        echo $_nameAfterChild->toHtml();
                    }
                }
                ?>

                <?php  
                    // get DISC label
                    $_finalPrice=$_product->getFinalPrice(); 
                    $_price=$_product->getPrice();
                    $_savePercent = 100 - round(($_finalPrice / $_price)*100) .'%';
                ?>
                <div class="price-wrapper <?php echo ($_finalPrice < $_price)? 'has-sale':'' ?>">
                    <?php echo $this->getPriceHtml($_product, true, '-upsell') ?>
                    <?php if($_finalPrice < $_price): ?>
                        <!-- discount label -->
                        <span class="label sale">
                            <?php echo $this->__('%s OFF', $_savePercent) ?>
                        </span>
                    <?php endif; ?>
                </div>

                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>

                <div class="bottom-part">
                    <?php  
                        // Get NEW label
                        $today =  time();
                        $news_from_date_value = $_product->getData('news_from_date');
                        $news_to_date_value   = $_product->getData('news_to_date');
                        $is_new = false;
                        if($news_from_date_value != null){
                            if($today >= strtotime( $news_from_date_value) && $today <= strtotime($news_to_date_value) || $today >= strtotime( $news_from_date_value) && is_null($news_to_date_value)){
                                $is_new = true;
                            }   
                        }
                    ?>

                    <?php if($is_new): ?>
                        <!-- new label -->
                        <span class="label new">
                            <?php echo $this->__('New Product') ?>
                        </span>
                    <?php endif; ?>

                    <?php //@TODO: add IF statement here ?>
                    <!-- installment label -->
                    <span class="label installment">
                        <?php echo $this->__('Cicilan 0%') ?>
                    </span>
                </div>

                <div class="actions">
                    <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                        <a href="javascript:void(0)" class="colorbox_iframe flaticon-eyes12 btn-quickview"></a>
                        <button type="button" title="<?php echo $this->quoteEscape($this->__('Buy Now')) ?>" class="button btn-cart" onclick="<?php if($isAjaxAddtoCart) : ?>addToCart<?php else : ?>setLocation<?php endif; ?>('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Buy Now') ?></span></span></button>
                    <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                        <a href="javascript:void(0)" class="colorbox_iframe flaticon-eyes12 btn-quickview"></a>
                        <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                </div>
            </div>
            </li>
        <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateList('recently-viewed-items');</script>
    </div>
</div>
<?php endif; ?>
