<?php
/**
 * Veritrans VT Web adminhtml info template
 *
 * @category   Mage
 * @package    vtwebbni/info.phtml
 * @author     Kisman Hong, plihplih.com
 * this template is used for payment method information at the right side, in progress bar.
 */
?>
    <!--<img src="<?php echo $this->getSkinUrl('images/Veritrans.png') ?>"/> -->
    <b><?php echo Mage::helper('vtwebbni/data')->_getTitle()?></b><br/>
<?php if($this->getOrder() && !is_null($this->getOrder()->getData('installment_tenor'))) : ?>
    <?php echo $this->__('Installment %s months', $this->getOrder()->getData('installment_tenor'));?>
<?php endif; ?>