<?php
/**
 * Edit Account template
 *
 * Description:
 * - Override rwd/default
 * - wrap with div.section
 * - Add telehone input field
 *
 * @category    design
 * @package     rwd_enterprise
 * @copyright Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license http://www.magento.com/license/enterprise-edition
 */
?>
<div class="section customer-account-edit">
    <form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" autocomplete="off" id="form-validate" class="scaffold-form" enctype="multipart/form-data">
        <div class="section-title">
            <h2><?php echo $this->__('Account Information') ?></h2>
        </div>
        <?php echo $this->getMessagesBlock()->toHtml() ?>
        <div class="fieldset">
            <?php echo $this->getBlockHtml('formkey')?>
            <h2 class="legend"><?php echo $this->__('Account Information') ?></h2>
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <div class="col2-set">
                <div class="col-1">
                    <ul class="form-list">
                        <li class="fields">
                            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
                        </li>
                        <li>
                            <label for="email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
                            <div class="input-box">
                                <input disabled="disabled" type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="email" value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" class="input-text required-entry validate-email" />
                            </div>
                        </li>
                        <li class="control">
                            <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Change Password')) ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="change_password"><?php echo $this->__('Click here to change password') ?></label>
                        </li>
                    </ul>
                </div>
                <div class="col-2">
                    <ul class="form-list">
                    <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                    <?php if ($_dob->isEnabled()): ?>
                        <li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
                    <?php endif ?>
                    <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                    <?php if ($_taxvat->isEnabled()): ?>
                        <li><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>
                    <?php endif ?>
                        <li>
                            <label for="telephone"><?php echo $this->__('Telephone Number') ?></label>
                            <div class="input-box">
                                <input type="text" value="<?php echo $this->getCustomer()->getTelephone(); ?>" title="<?php echo $this->__('Telephone') ?>" name="telephone" class="input-text validate-digits-range">
                            </div>
                        </li>
                    <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                    <?php if ($_gender->isEnabled()): ?>
                        <li class="control gender"><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></li>
                    <?php endif ?>
                    </ul>
                </div>
            </div>
        </div>
        <?php $userDefinedAttributes = $this->getLayout()->getBlock('customer_form_user_attributes'); ?>
        <?php if ($userDefinedAttributes):?>
            <?php echo $userDefinedAttributes->setEntity($this->getCustomer())->toHtml(); ?>
        <?php endif;?>
        <div class="fieldset" style="display:none;">
            <h2 class="legend"><?php echo $this->__('Change Password') ?></h2>
            <div class="col2-set">
                <div class="col-1">
                    <ul class="form-list">
                        <li>
                            <label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>
                            <div class="input-box">
                                <!-- This is a dummy hidden field to trick firefox from auto filling the password -->
                                <input type="text" class="input-text no-display" name="dummy" id="dummy" />
                                <input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Current Password')) ?>" class="input-text" name="current_password" id="current_password" />
                            </div>
                        </li>
                        <li class="fields">
                            <div class="field">
                                <label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
                                <div class="input-box">
                                    <input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('New Password')) ?>" class="input-text validate-password" name="password" id="password" />
                                </div>
                            </div>
                            <div class="field">
                                <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
                                <div class="input-box">
                                    <input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm New Password')) ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="buttons-set">
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save')) ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        function setPasswordForm(arg){
            if(arg){
                $('current_password').closest('.fieldset').show();
                $('current_password').addClassName('required-entry');
                $('password').addClassName('required-entry');
                $('confirmation').addClassName('required-entry');

            }else{
                $('current_password').closest('.fieldset').hide();
                $('current_password').removeClassName('required-entry');
                $('password').removeClassName('required-entry');
                $('confirmation').removeClassName('required-entry');
            }
        }

        <?php if($this->getCustomer()->getChangePassword()): ?>
            setPasswordForm(true);
        <?php endif; ?>
    //]]>
    </script>
</div>
