<?php
/**
 * Address Book template
 *
 * Description:
 * - Override rwd/default
 *
 * @category    design
 * @package     base_default
 * @copyright Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license http://www.magento.com/license/enterprise-edition
 */
?>
<?php
/**
 * Temlate for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 */
?>
<div class="section">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Address Book') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <div class="box-account">
        <div class="col2-set addresses-list ">
            <div class="col-1 addresses-primary">
                <div class="box-title">
                    <h3><?php echo $this->__('Billing Address') ?></h3>
                </div>
                <div class="box-content">
                    <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
                            <address>
                                <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                            </address>
                            <div class="actions"><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>" class="edit flaticon-pencil124"><?php echo $this->__('Edit') ?></a></div>
                    <?php else: ?>
                            <h3><?php echo $this->__('Default Billing Address') ?></h3>
                            <?php echo $this->__('You have no default billing address in your address book.') ?>
                    <?php endif ?>
                </div>
            </div>
            <div class="col-2 addresses-additional">
                <div class="box-title">
                    <h3><?php echo $this->__('Shipping Address') ?></h3>
                </div>
                <div class="box-content">
                    <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
                            <address>
                                <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                            </address>
                            <div class="actions"><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>" class="edit flaticon-pencil124"><?php echo $this->__('Edit') ?></a></div>
                    <?php else: ?>
                            <h3><?php echo $this->__('Default Shipping Address') ?></h3>
                            <p><?php echo $this->__('You have no default shipping address in your address book.') ?></p>
                    <?php endif ?>
                </div>
            </div>
        </div>

        <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
            <?php $i=0; foreach($_pAddsses as $_address): ?>
                <?php $i++; ?>
                <?php if ($i%2==1): ?>            
                <div class="col2-set addresses-list ">
                <?php endif ?>
                    <div class="<?php echo ($i%2==1)? 'col-1':'col-2' ?> addresses-additional">
                        <div class="box-title">
                            <h3><?php echo $this->__('Shipping Address') ?> <?php echo $i+1 ?></h3>
                        </div>
                        <div class="box-content">
                                    <address>
                                        <?php echo $this->getAddressHtml($_address) ?>
                                    </address>
                                    <div class="actions"><a href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>" class="edit flaticon-pencil124"><?php echo $this->__('Edit') ?></a><a href="#" class="link-remove flaticon-cross93" onclick="return deleteAddress('<?php echo $_address->getId() ?>');"><?php echo $this->__('Delete') ?></a></div>
                        </div>
                    </div>
                <?php if ($i%2==0): ?>            
                </div>
                <?php endif ?>
            <?php endforeach ?>

            <?php 
            $countAddses = $i;
            if ($countAddses%2==0): ?>
            <div class="col2-set addresses-list ">
                <div class="col-1 addresses-additional">
            <?php else: ?>
                <div class="col-2 addresses-additional">
            <?php endif ?>
                    <div class="box-title">
                        <h3><?php echo $this->__('Shipping Address') ?> <?php echo $countAddses+2 ?></h3>
                    </div>
                    <div class="box-content empty">
                        <div class="actions">
                            <a href="javascript:void(0)" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add New Address')) ?>" class="add flaticon-add64" onclick="window.location='<?php echo $this->getAddAddressUrl() ?>';"><?php echo $this->__('Add') ?></a>
                        </div>
                    </div>
                </div>
            </div>
        <?php else: ?>
            <div class="col2-set addresses-list ">
                <div class="col-1 addresses-additional">
                    <div class="box-title">
                        <h3><?php echo $this->__('Shipping Address') ?> 2</h3>
                    </div>
                    <div class="box-content empty">
                        <div class="actions">
                            <a href="javascript:void(0)" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add New Address')) ?>" class="add flaticon-add64" onclick="window.location='<?php echo $this->getAddAddressUrl() ?>';"><?php echo $this->__('Add') ?></a>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
<script type="text/javascript">
//<![CDATA[
    function deleteAddress(addressId) {
        if(confirm('<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Are you sure you want to delete this address?')) ?>')) {
            window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
        }
        return false;
    }
//]]>
</script>
