<?php
/**
 * Edit Address template
 *
 * Description:
 * - Override rwd/enterprise
 * - wrap with div.section
 * - Remove street 2
 * - Use input textarea for Street
 * - Add Kecamatan kelurahan
 * - change textarea street to be an input
 * - remove 35 char validation (set this validation from admin)
 *
 * @category    design
 * @package     rwd_enterprise
 * @copyright Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license http://www.magento.com/license/enterprise-edition
 */
?>
<?php
/**
 * Edit customer address template
 *
 * @see Mage_Customer_Block_Address_Edit
 */
?>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate" class="scaffold-form" enctype="multipart/form-data">
    <div class="section">
        <?php if($this->getTitle()): ?>
        <div class="page-title">
            <h1><?php echo $this->getTitle() ?></h1>
        </div>
        <?php endif; ?>
        <?php echo $this->getMessagesBlock()->toHtml() ?>
        <div class="fieldset left">
        <?php echo $this->getBlockHtml('formkey')?>
        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <h2 class="legend"><?php echo $this->__('Contact Information') ?></h2>
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <ul class="form-list">
                <li class="fields">
                    <?php echo $this->getNameBlockHtml() ?>
                </li>
                <li class="wide">
                    <label for="company"><?php echo $this->__('Company') ?></label>
                    <div class="input-box">
                        <input type="text" name="company" id="company" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company')) ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="tel" name="telephone" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text  <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="telephone" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="fax"><?php echo $this->__('Fax') ?></label>
                        <div class="input-box">
                            <input type="tel" name="fax" id="fax" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Fax')) ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" />
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="fieldset right">
            <h2 class="legend"><?php echo $this->__('Address') ?></h2>
            <ul class="form-list">
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <li class="wide">
                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            
                <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                <li class="wide">
                    <label for="vat_id"><?php echo $this->__('VAT Number') ?></label>
                    <div class="input-box">
                        <input type="text" name="vat_id" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('VAT Number')) ?>" id="vat_id" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                    </div>
                </li>
                <?php endif; ?>
                <li class="fields">
                	<div class="field">
                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                    <div class="field">
                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="region_id" name="region_id" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                               <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box" id="icubecity">
                            <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"  title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                        </div>
                    </div>
                    <div class="field">
	                    <label for="kecamatan" class="required"><em>*</em><?php echo $this->__('Kecamatan') ?></label>
	                    <div class="input-box" id="icubekecamatan">
	                        <input type="text" name="kecamatan" value="<?php echo $this->escapeHtml($this->getAddress()->getKecamatan()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Kecamatan')) ?>" id="kecamatan" class="input-text" />
                    	</div>
                	</div>
<!-- Hide this html for now -->
<!--
		            <div class="field">
		                <label for="kelurahan"><?php echo $this->__('Kelurahan') ?></label>
		                <div class="input-box">
		                    <input type="text" name="kelurahan" value="<?php echo $this->escapeHtml($this->getAddress()->getKelurahan()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Kelurahan')) ?>" id="kelurahan" class="input-text" />
		                </div>
		            </div>
-->
				<div class="field">
                    <div class="input-box" id="icubekodejalur" style="display: none">
                        <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Kode Jalur')) ?>" name="kodejalur" class="input-text" id="kodejalur" value="<?php echo $this->escapeHtml($this->getAddress()->getKodejalur()) ?>" />
                    </div>
                </div>
                <div class="field">
                    <div class="input-box" id="icubekodekecamatan" style="display: none">
                        <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Kode Kecamatan')) ?>" name="kodekecamatan" class="input-text" id="kodekecamatan" value="<?php echo $this->escapeHtml($this->getAddress()->getKodekecamatan()) ?>" />
                    </div>
                </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                        </div>
                    </div>
                </li>
                <?php $userDefinedAttributes = $this->getLayout()->getBlock('customer_form_user_attributes'); ?>
                <?php if ($userDefinedAttributes):?>
                    <?php echo $userDefinedAttributes->setEntity($this->getAddress())->setShowContainer(false)->toHtml(); ?>
                <?php endif;?>
                <li<?php if($this->canSetAsDefaultBilling()) echo ' class="control"' ?>>
                    <?php if($this->isDefaultBilling()): ?>
                        <strong><?php //echo $this->__('Default Billing Address') ?></strong>
                    <?php elseif($this->canSetAsDefaultBilling()): ?>
                        <input type="checkbox" id="primary_billing" name="default_billing" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Use as My Default Billing Address')) ?>" class="checkbox" /><label for="primary_billing"><?php echo $this->__('Use as my default billing address') ?></label>
                    <?php else: ?>
                        <input type="hidden" name="default_billing" value="1" />
                    <?php endif; ?>
                </li>
                <li<?php if($this->canSetAsDefaultShipping()) echo ' class="control"' ?>>
                    <?php if($this->isDefaultShipping()): ?>
                        <strong><?php //echo $this->__('Default Shipping Address') ?></strong>
                    <?php elseif($this->canSetAsDefaultShipping()): ?>
                        <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Use as My Default Shipping Address')) ?>" class="checkbox" /><label for="primary_shipping"><?php echo $this->__('Use as my default shipping address') ?></label>
                    <?php else: ?>
                        <input type="hidden" name="default_shipping" value="1" />
                    <?php endif; ?>
                </li>
            </ul>
        </div>
    </div>

    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save Address')) ?>" class="button"><span><span><?php echo $this->__('Save Address') ?></span></span></button>
    </div>
</form>

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
//]]>
</script>
<!-- Icube city kecamatan -->
<script type="text/javascript">
	jQuery(document).ready(function()
	{
		getCityAjax();
	});
	
	function getCityAjax()
	{
		var urlCity = '<?php echo Mage::getUrl('city/index/getMyAccountCityCollectionAjax',array('_secure'=>true)) ?>';
		jQuery('#icubecity').html('<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" width="30px" />');
	 jQuery.ajax({
                  url:  urlCity,
                  type: "POST",
                  data: {region: $('region_id').options[$('region_id').selectedIndex].value, defaultvalue:'<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>' },
                  success: function(data) {
                      if(data != '')
                      jQuery('#icubecity').html(data);
                      /* get Kecamatan Ajax */
                      getKecamatanAjax();
                      /* custom select */
                      changeSelect(jQuery('select#city'));
                      jQuery('select#city').change(function(){
                        jQuery(this).prev().find('span').text(jQuery(this).children("option").filter(":selected").text());
                      });
                  }
            });
 	}
 	
 	function getKecamatanAjax()
 	{
	 	var urlKec = '<?php echo Mage::getUrl('city/index/getMyAccountKecamatanCollectionAjax',array('_secure'=>true)) ?>';
		jQuery('#icubekecamatan').html('<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" width="30px" />');
		 jQuery.ajax({
		      url:  urlKec,
		      type: "POST",
		      data: {city: $('city').options[$('city').selectedIndex].value, defaultvalue:'<?php echo $this->escapeHtml($this->getAddress()->getKecamatan()) ?>'  },
		      success: function(data) {
		          if(data != '')
		          jQuery('#icubekecamatan').html(data);
		           /* get Kode Jalur */
				   getKodeAjax();
                  /* custom select */
                  changeSelect(jQuery('select#kecamatan'));
                  jQuery('select#kecamatan').change(function(){
                    jQuery(this).prev().find('span').text(jQuery(this).children("option").filter(":selected").text());
                  });
		      }
		});
	 }
	 
	  function getKodeAjax(){
		 var urlKj = '<?php echo Mage::getUrl('city/index/getKodeAjax',array('_secure'=>true)) ?>'; 
         jQuery('.my-account').addClass('loading');
		 jQuery.ajax({
		      url:  urlKj,
		      type: "POST",
		      data: {city: $('city').options[$('city').selectedIndex].value, kecamatan: $('kecamatan').options[$('kecamatan').selectedIndex].value  },
		      success: function(data) {
		          if(data != '')
		          data = jQuery.parseJSON(data);
                  jQuery("#kodejalur").val(data['kodejalur']);
                  jQuery("#kodekecamatan").val(data['kodekecamatan']);
                  jQuery('.my-account').removeClass('loading');
		      }
		});
	 }

	 $('region_id').on('change', function()
	 {
	    var country = $('country');
	    if(country.options[country.selectedIndex].value == 'ID'){
	        getCityAjax();
	    }
 	});
 	
 	$('country').on('change', function()
 	{
	    var country = $('country');
	    if(country.options[country.selectedIndex].value != 'ID')
	    {
		 jQuery('#icubecity').html('<input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" name="city" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" />');
		 jQuery('#icubekecamatan').html('<input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Kecamatan')) ?>" name="kecamatan" value="<?php echo $this->escapeHtml($this->getAddress()->getKecamatan()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('kecamatan') ?>" id="kecamatan" />');
         }
		 else
		 {
	        getCityAjax();
	    }
	});
	
</script>